// Code generated by ent, DO NOT EDIT.

package positionmark

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the positionmark type in the database.
	Label = "position_mark"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldNetOutputAmount holds the string denoting the net_output_amount field in the database.
	FieldNetOutputAmount = "net_output_amount"
	// FieldFeeEstimate holds the string denoting the fee_estimate field in the database.
	FieldFeeEstimate = "fee_estimate"
	// FieldReturnBps holds the string denoting the return_bps field in the database.
	FieldReturnBps = "return_bps"
	// FieldQuoteHash holds the string denoting the quote_hash field in the database.
	FieldQuoteHash = "quote_hash"
	// FieldRouteState holds the string denoting the route_state field in the database.
	FieldRouteState = "route_state"
	// FieldMfeBps holds the string denoting the mfe_bps field in the database.
	FieldMfeBps = "mfe_bps"
	// FieldMaeBps holds the string denoting the mae_bps field in the database.
	FieldMaeBps = "mae_bps"
	// FieldNoRouteCount holds the string denoting the no_route_count field in the database.
	FieldNoRouteCount = "no_route_count"
	// FieldObservedAt holds the string denoting the observed_at field in the database.
	FieldObservedAt = "observed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgePosition holds the string denoting the position edge name in mutations.
	EdgePosition = "position"
	// Table holds the table name of the positionmark in the database.
	Table = "position_marks"
	// PositionTable is the table that holds the position relation/edge.
	PositionTable = "position_marks"
	// PositionInverseTable is the table name for the PaperPosition entity.
	// It exists in this package in order to avoid circular dependency with the "paperposition" package.
	PositionInverseTable = "paper_positions"
	// PositionColumn is the table column denoting the position relation/edge.
	PositionColumn = "paper_position_marks"
)

// Columns holds all SQL columns for positionmark fields.
var Columns = []string{
	FieldID,
	FieldPrice,
	FieldNetOutputAmount,
	FieldFeeEstimate,
	FieldReturnBps,
	FieldQuoteHash,
	FieldRouteState,
	FieldMfeBps,
	FieldMaeBps,
	FieldNoRouteCount,
	FieldObservedAt,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "position_marks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"paper_position_marks",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// PriceValidator is a validator for the "price" field. It is called by the builders before save.
	PriceValidator func(string) error
	// FeeEstimateValidator is a validator for the "fee_estimate" field. It is called by the builders before save.
	FeeEstimateValidator func(int64) error
	// DefaultNoRouteCount holds the default value on creation for the "no_route_count" field.
	DefaultNoRouteCount int
	// NoRouteCountValidator is a validator for the "no_route_count" field. It is called by the builders before save.
	NoRouteCountValidator func(int) error
	// DefaultObservedAt holds the default value on creation for the "observed_at" field.
	DefaultObservedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// RouteState defines the type for the "route_state" enum field.
type RouteState string

// RouteStateEXECUTABLE is the default value of the RouteState enum.
const DefaultRouteState = RouteStateEXECUTABLE

// RouteState values.
const (
	RouteStateEXECUTABLE RouteState = "EXECUTABLE"
	RouteStateNO_ROUTE   RouteState = "NO_ROUTE"
)

func (rs RouteState) String() string {
	return string(rs)
}

// RouteStateValidator is a validator for the "route_state" field enum values. It is called by the builders before save.
func RouteStateValidator(rs RouteState) error {
	switch rs {
	case RouteStateEXECUTABLE, RouteStateNO_ROUTE:
		return nil
	default:
		return fmt.Errorf("positionmark: invalid enum value for route_state field: %q", rs)
	}
}

// OrderOption defines the ordering options for the PositionMark queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByNetOutputAmount orders the results by the net_output_amount field.
func ByNetOutputAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetOutputAmount, opts...).ToFunc()
}

// ByFeeEstimate orders the results by the fee_estimate field.
func ByFeeEstimate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeEstimate, opts...).ToFunc()
}

// ByReturnBps orders the results by the return_bps field.
func ByReturnBps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReturnBps, opts...).ToFunc()
}

// ByQuoteHash orders the results by the quote_hash field.
func ByQuoteHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuoteHash, opts...).ToFunc()
}

// ByRouteState orders the results by the route_state field.
func ByRouteState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRouteState, opts...).ToFunc()
}

// ByMfeBps orders the results by the mfe_bps field.
func ByMfeBps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMfeBps, opts...).ToFunc()
}

// ByMaeBps orders the results by the mae_bps field.
func ByMaeBps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaeBps, opts...).ToFunc()
}

// ByNoRouteCount orders the results by the no_route_count field.
func ByNoRouteCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNoRouteCount, opts...).ToFunc()
}

// ByObservedAt orders the results by the observed_at field.
func ByObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByPositionField orders the results by position field.
func ByPositionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPositionStep(), sql.OrderByField(field, opts...))
	}
}
func newPositionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PositionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PositionTable, PositionColumn),
	)
}
