// Code generated by ent, DO NOT EDIT.

package positionmark

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldLTE(FieldID, id))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldEQ(FieldPrice, v))
}

// ObservedAt applies equality check predicate on the "observed_at" field. It's identical to ObservedAtEQ.
func ObservedAt(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldEQ(FieldObservedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldEQ(FieldCreatedAt, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldLTE(FieldPrice, v))
}

// PriceContains applies the Contains predicate on the "price" field.
func PriceContains(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldContains(FieldPrice, v))
}

// PriceHasPrefix applies the HasPrefix predicate on the "price" field.
func PriceHasPrefix(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldHasPrefix(FieldPrice, v))
}

// PriceHasSuffix applies the HasSuffix predicate on the "price" field.
func PriceHasSuffix(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldHasSuffix(FieldPrice, v))
}

// PriceEqualFold applies the EqualFold predicate on the "price" field.
func PriceEqualFold(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldEqualFold(FieldPrice, v))
}

// PriceContainsFold applies the ContainsFold predicate on the "price" field.
func PriceContainsFold(v string) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldContainsFold(FieldPrice, v))
}

// ObservedAtEQ applies the EQ predicate on the "observed_at" field.
func ObservedAtEQ(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldEQ(FieldObservedAt, v))
}

// ObservedAtNEQ applies the NEQ predicate on the "observed_at" field.
func ObservedAtNEQ(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldNEQ(FieldObservedAt, v))
}

// ObservedAtIn applies the In predicate on the "observed_at" field.
func ObservedAtIn(vs ...time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldIn(FieldObservedAt, vs...))
}

// ObservedAtNotIn applies the NotIn predicate on the "observed_at" field.
func ObservedAtNotIn(vs ...time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldNotIn(FieldObservedAt, vs...))
}

// ObservedAtGT applies the GT predicate on the "observed_at" field.
func ObservedAtGT(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldGT(FieldObservedAt, v))
}

// ObservedAtGTE applies the GTE predicate on the "observed_at" field.
func ObservedAtGTE(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldGTE(FieldObservedAt, v))
}

// ObservedAtLT applies the LT predicate on the "observed_at" field.
func ObservedAtLT(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldLT(FieldObservedAt, v))
}

// ObservedAtLTE applies the LTE predicate on the "observed_at" field.
func ObservedAtLTE(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldLTE(FieldObservedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PositionMark {
	return predicate.PositionMark(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPosition applies the HasEdge predicate on the "position" edge.
func HasPosition() predicate.PositionMark {
	return predicate.PositionMark(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PositionTable, PositionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPositionWith applies the HasEdge predicate on the "position" edge with a given conditions (other predicates).
func HasPositionWith(preds ...predicate.PaperPosition) predicate.PositionMark {
	return predicate.PositionMark(func(s *sql.Selector) {
		step := newPositionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PositionMark) predicate.PositionMark {
	return predicate.PositionMark(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PositionMark) predicate.PositionMark {
	return predicate.PositionMark(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PositionMark) predicate.PositionMark {
	return predicate.PositionMark(sql.NotPredicates(p))
}
