// Code generated by ent, DO NOT EDIT.

package paperposition

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the paperposition type in the database.
	Label = "paper_position"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldNotionalMicros holds the string denoting the notional_micros field in the database.
	FieldNotionalMicros = "notional_micros"
	// FieldEntryPrice holds the string denoting the entry_price field in the database.
	FieldEntryPrice = "entry_price"
	// FieldTokenQuantity holds the string denoting the token_quantity field in the database.
	FieldTokenQuantity = "token_quantity"
	// FieldOpenedAt holds the string denoting the opened_at field in the database.
	FieldOpenedAt = "opened_at"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeCandidate holds the string denoting the candidate edge name in mutations.
	EdgeCandidate = "candidate"
	// EdgeMarks holds the string denoting the marks edge name in mutations.
	EdgeMarks = "marks"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// Table holds the table name of the paperposition in the database.
	Table = "paper_positions"
	// CandidateTable is the table that holds the candidate relation/edge.
	CandidateTable = "paper_positions"
	// CandidateInverseTable is the table name for the Candidate entity.
	// It exists in this package in order to avoid circular dependency with the "candidate" package.
	CandidateInverseTable = "candidates"
	// CandidateColumn is the table column denoting the candidate relation/edge.
	CandidateColumn = "candidate_positions"
	// MarksTable is the table that holds the marks relation/edge.
	MarksTable = "position_marks"
	// MarksInverseTable is the table name for the PositionMark entity.
	// It exists in this package in order to avoid circular dependency with the "positionmark" package.
	MarksInverseTable = "position_marks"
	// MarksColumn is the table column denoting the marks relation/edge.
	MarksColumn = "paper_position_marks"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "position_events"
	// EventsInverseTable is the table name for the PositionEvent entity.
	// It exists in this package in order to avoid circular dependency with the "positionevent" package.
	EventsInverseTable = "position_events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "paper_position_events"
)

// Columns holds all SQL columns for paperposition fields.
var Columns = []string{
	FieldID,
	FieldState,
	FieldNotionalMicros,
	FieldEntryPrice,
	FieldTokenQuantity,
	FieldOpenedAt,
	FieldClosedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "paper_positions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"candidate_positions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NotionalMicrosValidator is a validator for the "notional_micros" field. It is called by the builders before save.
	NotionalMicrosValidator func(int64) error
	// EntryPriceValidator is a validator for the "entry_price" field. It is called by the builders before save.
	EntryPriceValidator func(string) error
	// TokenQuantityValidator is a validator for the "token_quantity" field. It is called by the builders before save.
	TokenQuantityValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// State defines the type for the "state" enum field.
type State string

// State values.
const (
	StatePENDING    State = "PENDING"
	StateOPEN       State = "OPEN"
	StateCLOSING    State = "CLOSING"
	StateCLOSED     State = "CLOSED"
	StateUNSELLABLE State = "UNSELLABLE"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "state" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StatePENDING, StateOPEN, StateCLOSING, StateCLOSED, StateUNSELLABLE:
		return nil
	default:
		return fmt.Errorf("paperposition: invalid enum value for state field: %q", s)
	}
}

// OrderOption defines the ordering options for the PaperPosition queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByNotionalMicros orders the results by the notional_micros field.
func ByNotionalMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotionalMicros, opts...).ToFunc()
}

// ByEntryPrice orders the results by the entry_price field.
func ByEntryPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryPrice, opts...).ToFunc()
}

// ByTokenQuantity orders the results by the token_quantity field.
func ByTokenQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenQuantity, opts...).ToFunc()
}

// ByOpenedAt orders the results by the opened_at field.
func ByOpenedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOpenedAt, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCandidateField orders the results by candidate field.
func ByCandidateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCandidateStep(), sql.OrderByField(field, opts...))
	}
}

// ByMarksCount orders the results by marks count.
func ByMarksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMarksStep(), opts...)
	}
}

// ByMarks orders the results by marks terms.
func ByMarks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMarksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newCandidateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CandidateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CandidateTable, CandidateColumn),
	)
}
func newMarksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MarksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MarksTable, MarksColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
