// Code generated by ent, DO NOT EDIT.

package paperposition

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLTE(FieldID, id))
}

// NotionalMicros applies equality check predicate on the "notional_micros" field. It's identical to NotionalMicrosEQ.
func NotionalMicros(v int64) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldNotionalMicros, v))
}

// EntryPrice applies equality check predicate on the "entry_price" field. It's identical to EntryPriceEQ.
func EntryPrice(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldEntryPrice, v))
}

// TokenQuantity applies equality check predicate on the "token_quantity" field. It's identical to TokenQuantityEQ.
func TokenQuantity(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldTokenQuantity, v))
}

// OpenedAt applies equality check predicate on the "opened_at" field. It's identical to OpenedAtEQ.
func OpenedAt(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldOpenedAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldClosedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldUpdatedAt, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v State) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v State) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...State) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...State) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNotIn(FieldState, vs...))
}

// NotionalMicrosEQ applies the EQ predicate on the "notional_micros" field.
func NotionalMicrosEQ(v int64) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldNotionalMicros, v))
}

// NotionalMicrosNEQ applies the NEQ predicate on the "notional_micros" field.
func NotionalMicrosNEQ(v int64) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNEQ(FieldNotionalMicros, v))
}

// NotionalMicrosIn applies the In predicate on the "notional_micros" field.
func NotionalMicrosIn(vs ...int64) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldIn(FieldNotionalMicros, vs...))
}

// NotionalMicrosNotIn applies the NotIn predicate on the "notional_micros" field.
func NotionalMicrosNotIn(vs ...int64) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNotIn(FieldNotionalMicros, vs...))
}

// NotionalMicrosGT applies the GT predicate on the "notional_micros" field.
func NotionalMicrosGT(v int64) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGT(FieldNotionalMicros, v))
}

// NotionalMicrosGTE applies the GTE predicate on the "notional_micros" field.
func NotionalMicrosGTE(v int64) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGTE(FieldNotionalMicros, v))
}

// NotionalMicrosLT applies the LT predicate on the "notional_micros" field.
func NotionalMicrosLT(v int64) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLT(FieldNotionalMicros, v))
}

// NotionalMicrosLTE applies the LTE predicate on the "notional_micros" field.
func NotionalMicrosLTE(v int64) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLTE(FieldNotionalMicros, v))
}

// EntryPriceEQ applies the EQ predicate on the "entry_price" field.
func EntryPriceEQ(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldEntryPrice, v))
}

// EntryPriceNEQ applies the NEQ predicate on the "entry_price" field.
func EntryPriceNEQ(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNEQ(FieldEntryPrice, v))
}

// EntryPriceIn applies the In predicate on the "entry_price" field.
func EntryPriceIn(vs ...string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldIn(FieldEntryPrice, vs...))
}

// EntryPriceNotIn applies the NotIn predicate on the "entry_price" field.
func EntryPriceNotIn(vs ...string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNotIn(FieldEntryPrice, vs...))
}

// EntryPriceGT applies the GT predicate on the "entry_price" field.
func EntryPriceGT(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGT(FieldEntryPrice, v))
}

// EntryPriceGTE applies the GTE predicate on the "entry_price" field.
func EntryPriceGTE(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGTE(FieldEntryPrice, v))
}

// EntryPriceLT applies the LT predicate on the "entry_price" field.
func EntryPriceLT(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLT(FieldEntryPrice, v))
}

// EntryPriceLTE applies the LTE predicate on the "entry_price" field.
func EntryPriceLTE(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLTE(FieldEntryPrice, v))
}

// EntryPriceContains applies the Contains predicate on the "entry_price" field.
func EntryPriceContains(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldContains(FieldEntryPrice, v))
}

// EntryPriceHasPrefix applies the HasPrefix predicate on the "entry_price" field.
func EntryPriceHasPrefix(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldHasPrefix(FieldEntryPrice, v))
}

// EntryPriceHasSuffix applies the HasSuffix predicate on the "entry_price" field.
func EntryPriceHasSuffix(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldHasSuffix(FieldEntryPrice, v))
}

// EntryPriceEqualFold applies the EqualFold predicate on the "entry_price" field.
func EntryPriceEqualFold(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEqualFold(FieldEntryPrice, v))
}

// EntryPriceContainsFold applies the ContainsFold predicate on the "entry_price" field.
func EntryPriceContainsFold(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldContainsFold(FieldEntryPrice, v))
}

// TokenQuantityEQ applies the EQ predicate on the "token_quantity" field.
func TokenQuantityEQ(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldTokenQuantity, v))
}

// TokenQuantityNEQ applies the NEQ predicate on the "token_quantity" field.
func TokenQuantityNEQ(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNEQ(FieldTokenQuantity, v))
}

// TokenQuantityIn applies the In predicate on the "token_quantity" field.
func TokenQuantityIn(vs ...string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldIn(FieldTokenQuantity, vs...))
}

// TokenQuantityNotIn applies the NotIn predicate on the "token_quantity" field.
func TokenQuantityNotIn(vs ...string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNotIn(FieldTokenQuantity, vs...))
}

// TokenQuantityGT applies the GT predicate on the "token_quantity" field.
func TokenQuantityGT(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGT(FieldTokenQuantity, v))
}

// TokenQuantityGTE applies the GTE predicate on the "token_quantity" field.
func TokenQuantityGTE(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGTE(FieldTokenQuantity, v))
}

// TokenQuantityLT applies the LT predicate on the "token_quantity" field.
func TokenQuantityLT(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLT(FieldTokenQuantity, v))
}

// TokenQuantityLTE applies the LTE predicate on the "token_quantity" field.
func TokenQuantityLTE(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLTE(FieldTokenQuantity, v))
}

// TokenQuantityContains applies the Contains predicate on the "token_quantity" field.
func TokenQuantityContains(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldContains(FieldTokenQuantity, v))
}

// TokenQuantityHasPrefix applies the HasPrefix predicate on the "token_quantity" field.
func TokenQuantityHasPrefix(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldHasPrefix(FieldTokenQuantity, v))
}

// TokenQuantityHasSuffix applies the HasSuffix predicate on the "token_quantity" field.
func TokenQuantityHasSuffix(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldHasSuffix(FieldTokenQuantity, v))
}

// TokenQuantityEqualFold applies the EqualFold predicate on the "token_quantity" field.
func TokenQuantityEqualFold(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEqualFold(FieldTokenQuantity, v))
}

// TokenQuantityContainsFold applies the ContainsFold predicate on the "token_quantity" field.
func TokenQuantityContainsFold(v string) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldContainsFold(FieldTokenQuantity, v))
}

// OpenedAtEQ applies the EQ predicate on the "opened_at" field.
func OpenedAtEQ(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldOpenedAt, v))
}

// OpenedAtNEQ applies the NEQ predicate on the "opened_at" field.
func OpenedAtNEQ(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNEQ(FieldOpenedAt, v))
}

// OpenedAtIn applies the In predicate on the "opened_at" field.
func OpenedAtIn(vs ...time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldIn(FieldOpenedAt, vs...))
}

// OpenedAtNotIn applies the NotIn predicate on the "opened_at" field.
func OpenedAtNotIn(vs ...time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNotIn(FieldOpenedAt, vs...))
}

// OpenedAtGT applies the GT predicate on the "opened_at" field.
func OpenedAtGT(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGT(FieldOpenedAt, v))
}

// OpenedAtGTE applies the GTE predicate on the "opened_at" field.
func OpenedAtGTE(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGTE(FieldOpenedAt, v))
}

// OpenedAtLT applies the LT predicate on the "opened_at" field.
func OpenedAtLT(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLT(FieldOpenedAt, v))
}

// OpenedAtLTE applies the LTE predicate on the "opened_at" field.
func OpenedAtLTE(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLTE(FieldOpenedAt, v))
}

// OpenedAtIsNil applies the IsNil predicate on the "opened_at" field.
func OpenedAtIsNil() predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldIsNull(FieldOpenedAt))
}

// OpenedAtNotNil applies the NotNil predicate on the "opened_at" field.
func OpenedAtNotNil() predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNotNull(FieldOpenedAt))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNotNull(FieldClosedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PaperPosition {
	return predicate.PaperPosition(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasCandidate applies the HasEdge predicate on the "candidate" edge.
func HasCandidate() predicate.PaperPosition {
	return predicate.PaperPosition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CandidateTable, CandidateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCandidateWith applies the HasEdge predicate on the "candidate" edge with a given conditions (other predicates).
func HasCandidateWith(preds ...predicate.Candidate) predicate.PaperPosition {
	return predicate.PaperPosition(func(s *sql.Selector) {
		step := newCandidateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMarks applies the HasEdge predicate on the "marks" edge.
func HasMarks() predicate.PaperPosition {
	return predicate.PaperPosition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MarksTable, MarksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMarksWith applies the HasEdge predicate on the "marks" edge with a given conditions (other predicates).
func HasMarksWith(preds ...predicate.PositionMark) predicate.PaperPosition {
	return predicate.PaperPosition(func(s *sql.Selector) {
		step := newMarksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.PaperPosition {
	return predicate.PaperPosition(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.PositionEvent) predicate.PaperPosition {
	return predicate.PaperPosition(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaperPosition) predicate.PaperPosition {
	return predicate.PaperPosition(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaperPosition) predicate.PaperPosition {
	return predicate.PaperPosition(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaperPosition) predicate.PaperPosition {
	return predicate.PaperPosition(sql.NotPredicates(p))
}
