// Code generated by ent, DO NOT EDIT.

package socialsnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the socialsnapshot type in the database.
	Label = "social_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSocialEvidence holds the string denoting the social_evidence field in the database.
	FieldSocialEvidence = "social_evidence"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldObservedAt holds the string denoting the observed_at field in the database.
	FieldObservedAt = "observed_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeCandidate holds the string denoting the candidate edge name in mutations.
	EdgeCandidate = "candidate"
	// Table holds the table name of the socialsnapshot in the database.
	Table = "social_snapshots"
	// CandidateTable is the table that holds the candidate relation/edge.
	CandidateTable = "social_snapshots"
	// CandidateInverseTable is the table name for the Candidate entity.
	// It exists in this package in order to avoid circular dependency with the "candidate" package.
	CandidateInverseTable = "candidates"
	// CandidateColumn is the table column denoting the candidate relation/edge.
	CandidateColumn = "candidate_social_snapshots"
)

// Columns holds all SQL columns for socialsnapshot fields.
var Columns = []string{
	FieldID,
	FieldSocialEvidence,
	FieldScore,
	FieldObservedAt,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "social_snapshots"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"candidate_social_snapshots",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultObservedAt holds the default value on creation for the "observed_at" field.
	DefaultObservedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the SocialSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByObservedAt orders the results by the observed_at field.
func ByObservedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObservedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCandidateField orders the results by candidate field.
func ByCandidateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCandidateStep(), sql.OrderByField(field, opts...))
	}
}
func newCandidateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CandidateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CandidateTable, CandidateColumn),
	)
}
