// Code generated by ent, DO NOT EDIT.

package positionevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the positionevent type in the database.
	Label = "position_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldDetails holds the string denoting the details field in the database.
	FieldDetails = "details"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgePosition holds the string denoting the position edge name in mutations.
	EdgePosition = "position"
	// Table holds the table name of the positionevent in the database.
	Table = "position_events"
	// PositionTable is the table that holds the position relation/edge.
	PositionTable = "position_events"
	// PositionInverseTable is the table name for the PaperPosition entity.
	// It exists in this package in order to avoid circular dependency with the "paperposition" package.
	PositionInverseTable = "paper_positions"
	// PositionColumn is the table column denoting the position relation/edge.
	PositionColumn = "paper_position_events"
)

// Columns holds all SQL columns for positionevent fields.
var Columns = []string{
	FieldID,
	FieldEventType,
	FieldDetails,
	FieldCreatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "position_events"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"paper_position_events",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the PositionEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByPositionField orders the results by position field.
func ByPositionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPositionStep(), sql.OrderByField(field, opts...))
	}
}
func newPositionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PositionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PositionTable, PositionColumn),
	)
}
