// Code generated by ent, DO NOT EDIT.

package candidate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the candidate type in the database.
	Label = "candidate"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNetwork holds the string denoting the network field in the database.
	FieldNetwork = "network"
	// FieldMintAddress holds the string denoting the mint_address field in the database.
	FieldMintAddress = "mint_address"
	// FieldPoolAddress holds the string denoting the pool_address field in the database.
	FieldPoolAddress = "pool_address"
	// FieldDiscoveredAt holds the string denoting the discovered_at field in the database.
	FieldDiscoveredAt = "discovered_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSnapshots holds the string denoting the snapshots edge name in mutations.
	EdgeSnapshots = "snapshots"
	// EdgeSocialSnapshots holds the string denoting the social_snapshots edge name in mutations.
	EdgeSocialSnapshots = "social_snapshots"
	// EdgeVerdicts holds the string denoting the verdicts edge name in mutations.
	EdgeVerdicts = "verdicts"
	// EdgeDecisions holds the string denoting the decisions edge name in mutations.
	EdgeDecisions = "decisions"
	// EdgePositions holds the string denoting the positions edge name in mutations.
	EdgePositions = "positions"
	// Table holds the table name of the candidate in the database.
	Table = "candidates"
	// SnapshotsTable is the table that holds the snapshots relation/edge.
	SnapshotsTable = "candidate_snapshots"
	// SnapshotsInverseTable is the table name for the CandidateSnapshot entity.
	// It exists in this package in order to avoid circular dependency with the "candidatesnapshot" package.
	SnapshotsInverseTable = "candidate_snapshots"
	// SnapshotsColumn is the table column denoting the snapshots relation/edge.
	SnapshotsColumn = "candidate_snapshots"
	// SocialSnapshotsTable is the table that holds the social_snapshots relation/edge.
	SocialSnapshotsTable = "social_snapshots"
	// SocialSnapshotsInverseTable is the table name for the SocialSnapshot entity.
	// It exists in this package in order to avoid circular dependency with the "socialsnapshot" package.
	SocialSnapshotsInverseTable = "social_snapshots"
	// SocialSnapshotsColumn is the table column denoting the social_snapshots relation/edge.
	SocialSnapshotsColumn = "candidate_social_snapshots"
	// VerdictsTable is the table that holds the verdicts relation/edge.
	VerdictsTable = "verdicts"
	// VerdictsInverseTable is the table name for the Verdict entity.
	// It exists in this package in order to avoid circular dependency with the "verdict" package.
	VerdictsInverseTable = "verdicts"
	// VerdictsColumn is the table column denoting the verdicts relation/edge.
	VerdictsColumn = "candidate_verdicts"
	// DecisionsTable is the table that holds the decisions relation/edge.
	DecisionsTable = "trade_decisions"
	// DecisionsInverseTable is the table name for the TradeDecision entity.
	// It exists in this package in order to avoid circular dependency with the "tradedecision" package.
	DecisionsInverseTable = "trade_decisions"
	// DecisionsColumn is the table column denoting the decisions relation/edge.
	DecisionsColumn = "candidate_decisions"
	// PositionsTable is the table that holds the positions relation/edge.
	PositionsTable = "paper_positions"
	// PositionsInverseTable is the table name for the PaperPosition entity.
	// It exists in this package in order to avoid circular dependency with the "paperposition" package.
	PositionsInverseTable = "paper_positions"
	// PositionsColumn is the table column denoting the positions relation/edge.
	PositionsColumn = "candidate_positions"
)

// Columns holds all SQL columns for candidate fields.
var Columns = []string{
	FieldID,
	FieldNetwork,
	FieldMintAddress,
	FieldPoolAddress,
	FieldDiscoveredAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NetworkValidator is a validator for the "network" field. It is called by the builders before save.
	NetworkValidator func(string) error
	// MintAddressValidator is a validator for the "mint_address" field. It is called by the builders before save.
	MintAddressValidator func(string) error
	// PoolAddressValidator is a validator for the "pool_address" field. It is called by the builders before save.
	PoolAddressValidator func(string) error
	// DefaultDiscoveredAt holds the default value on creation for the "discovered_at" field.
	DefaultDiscoveredAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Candidate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNetwork orders the results by the network field.
func ByNetwork(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetwork, opts...).ToFunc()
}

// ByMintAddress orders the results by the mint_address field.
func ByMintAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMintAddress, opts...).ToFunc()
}

// ByPoolAddress orders the results by the pool_address field.
func ByPoolAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPoolAddress, opts...).ToFunc()
}

// ByDiscoveredAt orders the results by the discovered_at field.
func ByDiscoveredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscoveredAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySnapshotsCount orders the results by snapshots count.
func BySnapshotsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSnapshotsStep(), opts...)
	}
}

// BySnapshots orders the results by snapshots terms.
func BySnapshots(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSnapshotsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySocialSnapshotsCount orders the results by social_snapshots count.
func BySocialSnapshotsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSocialSnapshotsStep(), opts...)
	}
}

// BySocialSnapshots orders the results by social_snapshots terms.
func BySocialSnapshots(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSocialSnapshotsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByVerdictsCount orders the results by verdicts count.
func ByVerdictsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVerdictsStep(), opts...)
	}
}

// ByVerdicts orders the results by verdicts terms.
func ByVerdicts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVerdictsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDecisionsCount orders the results by decisions count.
func ByDecisionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDecisionsStep(), opts...)
	}
}

// ByDecisions orders the results by decisions terms.
func ByDecisions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDecisionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPositionsCount orders the results by positions count.
func ByPositionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPositionsStep(), opts...)
	}
}

// ByPositions orders the results by positions terms.
func ByPositions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPositionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSnapshotsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SnapshotsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SnapshotsTable, SnapshotsColumn),
	)
}
func newSocialSnapshotsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SocialSnapshotsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SocialSnapshotsTable, SocialSnapshotsColumn),
	)
}
func newVerdictsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VerdictsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VerdictsTable, VerdictsColumn),
	)
}
func newDecisionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DecisionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DecisionsTable, DecisionsColumn),
	)
}
func newPositionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PositionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PositionsTable, PositionsColumn),
	)
}
