// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIUsagesColumns holds the columns for the "api_usages" table.
	APIUsagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "utc_date", Type: field.TypeTime},
		{Name: "request_count", Type: field.TypeInt},
		{Name: "failure_count", Type: field.TypeInt},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// APIUsagesTable holds the schema information for the "api_usages" table.
	APIUsagesTable = &schema.Table{
		Name:       "api_usages",
		Columns:    APIUsagesColumns,
		PrimaryKey: []*schema.Column{APIUsagesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "apiusage_provider_utc_date",
				Unique:  true,
				Columns: []*schema.Column{APIUsagesColumns[1], APIUsagesColumns[2]},
			},
		},
	}
	// BotStatesColumns holds the columns for the "bot_states" table.
	BotStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "state_key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BotStatesTable holds the schema information for the "bot_states" table.
	BotStatesTable = &schema.Table{
		Name:       "bot_states",
		Columns:    BotStatesColumns,
		PrimaryKey: []*schema.Column{BotStatesColumns[0]},
	}
	// CandidatesColumns holds the columns for the "candidates" table.
	CandidatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "network", Type: field.TypeString},
		{Name: "mint_address", Type: field.TypeString},
		{Name: "pool_address", Type: field.TypeString},
		{Name: "discovered_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CandidatesTable holds the schema information for the "candidates" table.
	CandidatesTable = &schema.Table{
		Name:       "candidates",
		Columns:    CandidatesColumns,
		PrimaryKey: []*schema.Column{CandidatesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "candidate_network_mint_address_pool_address",
				Unique:  true,
				Columns: []*schema.Column{CandidatesColumns[1], CandidatesColumns[2], CandidatesColumns[3]},
			},
		},
	}
	// CandidateSnapshotsColumns holds the columns for the "candidate_snapshots" table.
	CandidateSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "market_evidence", Type: field.TypeJSON},
		{Name: "observed_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "candidate_snapshots", Type: field.TypeInt},
	}
	// CandidateSnapshotsTable holds the schema information for the "candidate_snapshots" table.
	CandidateSnapshotsTable = &schema.Table{
		Name:       "candidate_snapshots",
		Columns:    CandidateSnapshotsColumns,
		PrimaryKey: []*schema.Column{CandidateSnapshotsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "candidate_snapshots_candidates_snapshots",
				Columns:    []*schema.Column{CandidateSnapshotsColumns[4]},
				RefColumns: []*schema.Column{CandidatesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// DailyResultsColumns holds the columns for the "daily_results" table.
	DailyResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "utc_date", Type: field.TypeTime},
		{Name: "strategy_version", Type: field.TypeString},
		{Name: "daily_admitted_count", Type: field.TypeInt},
		{Name: "realized_pnl_micros", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// DailyResultsTable holds the schema information for the "daily_results" table.
	DailyResultsTable = &schema.Table{
		Name:       "daily_results",
		Columns:    DailyResultsColumns,
		PrimaryKey: []*schema.Column{DailyResultsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "dailyresult_utc_date_strategy_version",
				Unique:  true,
				Columns: []*schema.Column{DailyResultsColumns[1], DailyResultsColumns[2]},
			},
		},
	}
	// PaperPositionsColumns holds the columns for the "paper_positions" table.
	PaperPositionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"PENDING", "OPEN", "CLOSING", "CLOSED", "UNSELLABLE"}},
		{Name: "notional_micros", Type: field.TypeInt64},
		{Name: "strategy_version", Type: field.TypeString, Default: "legacy-unattributed"},
		{Name: "no_route_count", Type: field.TypeInt, Default: 0},
		{Name: "quote_mint", Type: field.TypeString, Nullable: true},
		{Name: "mint_address", Type: field.TypeString, Nullable: true},
		{Name: "entry_price", Type: field.TypeString, Nullable: true},
		{Name: "entry_input_amount", Type: field.TypeString, Nullable: true},
		{Name: "entry_network_fee_micros", Type: field.TypeInt64, Nullable: true},
		{Name: "entry_priority_fee_micros", Type: field.TypeInt64, Nullable: true},
		{Name: "token_quantity", Type: field.TypeString, Nullable: true},
		{Name: "opened_at", Type: field.TypeTime, Nullable: true},
		{Name: "closed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "candidate_positions", Type: field.TypeInt},
		{Name: "trade_decision_position", Type: field.TypeInt, Unique: true},
	}
	// PaperPositionsTable holds the schema information for the "paper_positions" table.
	PaperPositionsTable = &schema.Table{
		Name:       "paper_positions",
		Columns:    PaperPositionsColumns,
		PrimaryKey: []*schema.Column{PaperPositionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "paper_positions_candidates_positions",
				Columns:    []*schema.Column{PaperPositionsColumns[16]},
				RefColumns: []*schema.Column{CandidatesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "paper_positions_trade_decisions_position",
				Columns:    []*schema.Column{PaperPositionsColumns[17]},
				RefColumns: []*schema.Column{TradeDecisionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PositionEventsColumns holds the columns for the "position_events" table.
	PositionEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "event_type", Type: field.TypeString},
		{Name: "details", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "paper_position_events", Type: field.TypeInt},
	}
	// PositionEventsTable holds the schema information for the "position_events" table.
	PositionEventsTable = &schema.Table{
		Name:       "position_events",
		Columns:    PositionEventsColumns,
		PrimaryKey: []*schema.Column{PositionEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "position_events_paper_positions_events",
				Columns:    []*schema.Column{PositionEventsColumns[4]},
				RefColumns: []*schema.Column{PaperPositionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PositionMarksColumns holds the columns for the "position_marks" table.
	PositionMarksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "price", Type: field.TypeString},
		{Name: "net_output_amount", Type: field.TypeString, Nullable: true},
		{Name: "fee_estimate", Type: field.TypeInt64, Nullable: true},
		{Name: "return_bps", Type: field.TypeInt64, Nullable: true},
		{Name: "quote_hash", Type: field.TypeString, Nullable: true},
		{Name: "route_state", Type: field.TypeEnum, Enums: []string{"EXECUTABLE", "NO_ROUTE"}, Default: "EXECUTABLE"},
		{Name: "mfe_bps", Type: field.TypeInt64, Nullable: true},
		{Name: "mae_bps", Type: field.TypeInt64, Nullable: true},
		{Name: "no_route_count", Type: field.TypeInt, Default: 0},
		{Name: "observed_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "paper_position_marks", Type: field.TypeInt},
	}
	// PositionMarksTable holds the schema information for the "position_marks" table.
	PositionMarksTable = &schema.Table{
		Name:       "position_marks",
		Columns:    PositionMarksColumns,
		PrimaryKey: []*schema.Column{PositionMarksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "position_marks_paper_positions_marks",
				Columns:    []*schema.Column{PositionMarksColumns[12]},
				RefColumns: []*schema.Column{PaperPositionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SocialSnapshotsColumns holds the columns for the "social_snapshots" table.
	SocialSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "social_evidence", Type: field.TypeJSON},
		{Name: "score", Type: field.TypeInt},
		{Name: "observed_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "candidate_social_snapshots", Type: field.TypeInt},
	}
	// SocialSnapshotsTable holds the schema information for the "social_snapshots" table.
	SocialSnapshotsTable = &schema.Table{
		Name:       "social_snapshots",
		Columns:    SocialSnapshotsColumns,
		PrimaryKey: []*schema.Column{SocialSnapshotsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "social_snapshots_candidates_social_snapshots",
				Columns:    []*schema.Column{SocialSnapshotsColumns[5]},
				RefColumns: []*schema.Column{CandidatesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// TradeDecisionsColumns holds the columns for the "trade_decisions" table.
	TradeDecisionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "idempotency_key", Type: field.TypeString},
		{Name: "outcome", Type: field.TypeString},
		{Name: "rule_results", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "candidate_decisions", Type: field.TypeInt},
	}
	// TradeDecisionsTable holds the schema information for the "trade_decisions" table.
	TradeDecisionsTable = &schema.Table{
		Name:       "trade_decisions",
		Columns:    TradeDecisionsColumns,
		PrimaryKey: []*schema.Column{TradeDecisionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "trade_decisions_candidates_decisions",
				Columns:    []*schema.Column{TradeDecisionsColumns[5]},
				RefColumns: []*schema.Column{CandidatesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tradedecision_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{TradeDecisionsColumns[1]},
			},
		},
	}
	// VerdictsColumns holds the columns for the "verdicts" table.
	VerdictsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "model", Type: field.TypeString},
		{Name: "outcome", Type: field.TypeString},
		{Name: "evidence", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "candidate_verdicts", Type: field.TypeInt},
	}
	// VerdictsTable holds the schema information for the "verdicts" table.
	VerdictsTable = &schema.Table{
		Name:       "verdicts",
		Columns:    VerdictsColumns,
		PrimaryKey: []*schema.Column{VerdictsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "verdicts_candidates_verdicts",
				Columns:    []*schema.Column{VerdictsColumns[6]},
				RefColumns: []*schema.Column{CandidatesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIUsagesTable,
		BotStatesTable,
		CandidatesTable,
		CandidateSnapshotsTable,
		DailyResultsTable,
		PaperPositionsTable,
		PositionEventsTable,
		PositionMarksTable,
		SocialSnapshotsTable,
		TradeDecisionsTable,
		VerdictsTable,
	}
)

func init() {
	CandidateSnapshotsTable.ForeignKeys[0].RefTable = CandidatesTable
	PaperPositionsTable.ForeignKeys[0].RefTable = CandidatesTable
	PaperPositionsTable.ForeignKeys[1].RefTable = TradeDecisionsTable
	PositionEventsTable.ForeignKeys[0].RefTable = PaperPositionsTable
	PositionMarksTable.ForeignKeys[0].RefTable = PaperPositionsTable
	SocialSnapshotsTable.ForeignKeys[0].RefTable = CandidatesTable
	TradeDecisionsTable.ForeignKeys[0].RefTable = CandidatesTable
	VerdictsTable.ForeignKeys[0].RefTable = CandidatesTable
}
