// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/apiusage"
)

// APIUsageCreate is the builder for creating a APIUsage entity.
type APIUsageCreate struct {
	config
	mutation *APIUsageMutation
	hooks    []Hook
}

// SetProvider sets the "provider" field.
func (_c *APIUsageCreate) SetProvider(v string) *APIUsageCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetUtcDate sets the "utc_date" field.
func (_c *APIUsageCreate) SetUtcDate(v time.Time) *APIUsageCreate {
	_c.mutation.SetUtcDate(v)
	return _c
}

// SetRequestCount sets the "request_count" field.
func (_c *APIUsageCreate) SetRequestCount(v int) *APIUsageCreate {
	_c.mutation.SetRequestCount(v)
	return _c
}

// SetFailureCount sets the "failure_count" field.
func (_c *APIUsageCreate) SetFailureCount(v int) *APIUsageCreate {
	_c.mutation.SetFailureCount(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIUsageCreate) SetCreatedAt(v time.Time) *APIUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APIUsageCreate) SetNillableCreatedAt(v *time.Time) *APIUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APIUsageCreate) SetUpdatedAt(v time.Time) *APIUsageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APIUsageCreate) SetNillableUpdatedAt(v *time.Time) *APIUsageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the APIUsageMutation object of the builder.
func (_c *APIUsageCreate) Mutation() *APIUsageMutation {
	return _c.mutation
}

// Save creates the APIUsage in the database.
func (_c *APIUsageCreate) Save(ctx context.Context) (*APIUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIUsageCreate) SaveX(ctx context.Context) *APIUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIUsageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apiusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apiusage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIUsageCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "APIUsage.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := apiusage.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "APIUsage.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UtcDate(); !ok {
		return &ValidationError{Name: "utc_date", err: errors.New(`ent: missing required field "APIUsage.utc_date"`)}
	}
	if _, ok := _c.mutation.RequestCount(); !ok {
		return &ValidationError{Name: "request_count", err: errors.New(`ent: missing required field "APIUsage.request_count"`)}
	}
	if v, ok := _c.mutation.RequestCount(); ok {
		if err := apiusage.RequestCountValidator(v); err != nil {
			return &ValidationError{Name: "request_count", err: fmt.Errorf(`ent: validator failed for field "APIUsage.request_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.FailureCount(); !ok {
		return &ValidationError{Name: "failure_count", err: errors.New(`ent: missing required field "APIUsage.failure_count"`)}
	}
	if v, ok := _c.mutation.FailureCount(); ok {
		if err := apiusage.FailureCountValidator(v); err != nil {
			return &ValidationError{Name: "failure_count", err: fmt.Errorf(`ent: validator failed for field "APIUsage.failure_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIUsage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "APIUsage.updated_at"`)}
	}
	return nil
}

func (_c *APIUsageCreate) sqlSave(ctx context.Context) (*APIUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIUsageCreate) createSpec() (*APIUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &APIUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apiusage.Table, sqlgraph.NewFieldSpec(apiusage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(apiusage.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.UtcDate(); ok {
		_spec.SetField(apiusage.FieldUtcDate, field.TypeTime, value)
		_node.UtcDate = value
	}
	if value, ok := _c.mutation.RequestCount(); ok {
		_spec.SetField(apiusage.FieldRequestCount, field.TypeInt, value)
		_node.RequestCount = value
	}
	if value, ok := _c.mutation.FailureCount(); ok {
		_spec.SetField(apiusage.FieldFailureCount, field.TypeInt, value)
		_node.FailureCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apiusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apiusage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// APIUsageCreateBulk is the builder for creating many APIUsage entities in bulk.
type APIUsageCreateBulk struct {
	config
	err      error
	builders []*APIUsageCreate
}

// Save creates the APIUsage entities in the database.
func (_c *APIUsageCreateBulk) Save(ctx context.Context) ([]*APIUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIUsageCreateBulk) SaveX(ctx context.Context) []*APIUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
