// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/botstate"
)

// BotStateCreate is the builder for creating a BotState entity.
type BotStateCreate struct {
	config
	mutation *BotStateMutation
	hooks    []Hook
}

// SetStateKey sets the "state_key" field.
func (_c *BotStateCreate) SetStateKey(v string) *BotStateCreate {
	_c.mutation.SetStateKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *BotStateCreate) SetValue(v map[string]interface{}) *BotStateCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BotStateCreate) SetCreatedAt(v time.Time) *BotStateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BotStateCreate) SetNillableCreatedAt(v *time.Time) *BotStateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BotStateCreate) SetUpdatedAt(v time.Time) *BotStateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BotStateCreate) SetNillableUpdatedAt(v *time.Time) *BotStateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the BotStateMutation object of the builder.
func (_c *BotStateCreate) Mutation() *BotStateMutation {
	return _c.mutation
}

// Save creates the BotState in the database.
func (_c *BotStateCreate) Save(ctx context.Context) (*BotState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BotStateCreate) SaveX(ctx context.Context) *BotState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BotStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BotStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BotStateCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := botstate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := botstate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BotStateCreate) check() error {
	if _, ok := _c.mutation.StateKey(); !ok {
		return &ValidationError{Name: "state_key", err: errors.New(`ent: missing required field "BotState.state_key"`)}
	}
	if v, ok := _c.mutation.StateKey(); ok {
		if err := botstate.StateKeyValidator(v); err != nil {
			return &ValidationError{Name: "state_key", err: fmt.Errorf(`ent: validator failed for field "BotState.state_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "BotState.value"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BotState.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BotState.updated_at"`)}
	}
	return nil
}

func (_c *BotStateCreate) sqlSave(ctx context.Context) (*BotState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BotStateCreate) createSpec() (*BotState, *sqlgraph.CreateSpec) {
	var (
		_node = &BotState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(botstate.Table, sqlgraph.NewFieldSpec(botstate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.StateKey(); ok {
		_spec.SetField(botstate.FieldStateKey, field.TypeString, value)
		_node.StateKey = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(botstate.FieldValue, field.TypeJSON, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(botstate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(botstate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// BotStateCreateBulk is the builder for creating many BotState entities in bulk.
type BotStateCreateBulk struct {
	config
	err      error
	builders []*BotStateCreate
}

// Save creates the BotState entities in the database.
func (_c *BotStateCreateBulk) Save(ctx context.Context) ([]*BotState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BotState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BotStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BotStateCreateBulk) SaveX(ctx context.Context) []*BotState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BotStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BotStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
