// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/candidatesnapshot"
)

// CandidateSnapshotCreate is the builder for creating a CandidateSnapshot entity.
type CandidateSnapshotCreate struct {
	config
	mutation *CandidateSnapshotMutation
	hooks    []Hook
}

// SetMarketEvidence sets the "market_evidence" field.
func (_c *CandidateSnapshotCreate) SetMarketEvidence(v map[string]interface{}) *CandidateSnapshotCreate {
	_c.mutation.SetMarketEvidence(v)
	return _c
}

// SetObservedAt sets the "observed_at" field.
func (_c *CandidateSnapshotCreate) SetObservedAt(v time.Time) *CandidateSnapshotCreate {
	_c.mutation.SetObservedAt(v)
	return _c
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_c *CandidateSnapshotCreate) SetNillableObservedAt(v *time.Time) *CandidateSnapshotCreate {
	if v != nil {
		_c.SetObservedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CandidateSnapshotCreate) SetCreatedAt(v time.Time) *CandidateSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CandidateSnapshotCreate) SetNillableCreatedAt(v *time.Time) *CandidateSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_c *CandidateSnapshotCreate) SetCandidateID(id int) *CandidateSnapshotCreate {
	_c.mutation.SetCandidateID(id)
	return _c
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_c *CandidateSnapshotCreate) SetCandidate(v *Candidate) *CandidateSnapshotCreate {
	return _c.SetCandidateID(v.ID)
}

// Mutation returns the CandidateSnapshotMutation object of the builder.
func (_c *CandidateSnapshotCreate) Mutation() *CandidateSnapshotMutation {
	return _c.mutation
}

// Save creates the CandidateSnapshot in the database.
func (_c *CandidateSnapshotCreate) Save(ctx context.Context) (*CandidateSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CandidateSnapshotCreate) SaveX(ctx context.Context) *CandidateSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CandidateSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CandidateSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CandidateSnapshotCreate) defaults() {
	if _, ok := _c.mutation.ObservedAt(); !ok {
		v := candidatesnapshot.DefaultObservedAt()
		_c.mutation.SetObservedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := candidatesnapshot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CandidateSnapshotCreate) check() error {
	if _, ok := _c.mutation.MarketEvidence(); !ok {
		return &ValidationError{Name: "market_evidence", err: errors.New(`ent: missing required field "CandidateSnapshot.market_evidence"`)}
	}
	if _, ok := _c.mutation.ObservedAt(); !ok {
		return &ValidationError{Name: "observed_at", err: errors.New(`ent: missing required field "CandidateSnapshot.observed_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CandidateSnapshot.created_at"`)}
	}
	if len(_c.mutation.CandidateIDs()) == 0 {
		return &ValidationError{Name: "candidate", err: errors.New(`ent: missing required edge "CandidateSnapshot.candidate"`)}
	}
	return nil
}

func (_c *CandidateSnapshotCreate) sqlSave(ctx context.Context) (*CandidateSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CandidateSnapshotCreate) createSpec() (*CandidateSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &CandidateSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(candidatesnapshot.Table, sqlgraph.NewFieldSpec(candidatesnapshot.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.MarketEvidence(); ok {
		_spec.SetField(candidatesnapshot.FieldMarketEvidence, field.TypeJSON, value)
		_node.MarketEvidence = value
	}
	if value, ok := _c.mutation.ObservedAt(); ok {
		_spec.SetField(candidatesnapshot.FieldObservedAt, field.TypeTime, value)
		_node.ObservedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(candidatesnapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   candidatesnapshot.CandidateTable,
			Columns: []string{candidatesnapshot.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.candidate_snapshots = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CandidateSnapshotCreateBulk is the builder for creating many CandidateSnapshot entities in bulk.
type CandidateSnapshotCreateBulk struct {
	config
	err      error
	builders []*CandidateSnapshotCreate
}

// Save creates the CandidateSnapshot entities in the database.
func (_c *CandidateSnapshotCreateBulk) Save(ctx context.Context) ([]*CandidateSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CandidateSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CandidateSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CandidateSnapshotCreateBulk) SaveX(ctx context.Context) []*CandidateSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CandidateSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CandidateSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
