// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/candidatesnapshot"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/socialsnapshot"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/tradedecision"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/verdict"
)

// CandidateCreate is the builder for creating a Candidate entity.
type CandidateCreate struct {
	config
	mutation *CandidateMutation
	hooks    []Hook
}

// SetNetwork sets the "network" field.
func (_c *CandidateCreate) SetNetwork(v string) *CandidateCreate {
	_c.mutation.SetNetwork(v)
	return _c
}

// SetMintAddress sets the "mint_address" field.
func (_c *CandidateCreate) SetMintAddress(v string) *CandidateCreate {
	_c.mutation.SetMintAddress(v)
	return _c
}

// SetPoolAddress sets the "pool_address" field.
func (_c *CandidateCreate) SetPoolAddress(v string) *CandidateCreate {
	_c.mutation.SetPoolAddress(v)
	return _c
}

// SetDiscoveredAt sets the "discovered_at" field.
func (_c *CandidateCreate) SetDiscoveredAt(v time.Time) *CandidateCreate {
	_c.mutation.SetDiscoveredAt(v)
	return _c
}

// SetNillableDiscoveredAt sets the "discovered_at" field if the given value is not nil.
func (_c *CandidateCreate) SetNillableDiscoveredAt(v *time.Time) *CandidateCreate {
	if v != nil {
		_c.SetDiscoveredAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CandidateCreate) SetCreatedAt(v time.Time) *CandidateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CandidateCreate) SetNillableCreatedAt(v *time.Time) *CandidateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CandidateCreate) SetUpdatedAt(v time.Time) *CandidateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CandidateCreate) SetNillableUpdatedAt(v *time.Time) *CandidateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// AddSnapshotIDs adds the "snapshots" edge to the CandidateSnapshot entity by IDs.
func (_c *CandidateCreate) AddSnapshotIDs(ids ...int) *CandidateCreate {
	_c.mutation.AddSnapshotIDs(ids...)
	return _c
}

// AddSnapshots adds the "snapshots" edges to the CandidateSnapshot entity.
func (_c *CandidateCreate) AddSnapshots(v ...*CandidateSnapshot) *CandidateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSnapshotIDs(ids...)
}

// AddSocialSnapshotIDs adds the "social_snapshots" edge to the SocialSnapshot entity by IDs.
func (_c *CandidateCreate) AddSocialSnapshotIDs(ids ...int) *CandidateCreate {
	_c.mutation.AddSocialSnapshotIDs(ids...)
	return _c
}

// AddSocialSnapshots adds the "social_snapshots" edges to the SocialSnapshot entity.
func (_c *CandidateCreate) AddSocialSnapshots(v ...*SocialSnapshot) *CandidateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSocialSnapshotIDs(ids...)
}

// AddVerdictIDs adds the "verdicts" edge to the Verdict entity by IDs.
func (_c *CandidateCreate) AddVerdictIDs(ids ...int) *CandidateCreate {
	_c.mutation.AddVerdictIDs(ids...)
	return _c
}

// AddVerdicts adds the "verdicts" edges to the Verdict entity.
func (_c *CandidateCreate) AddVerdicts(v ...*Verdict) *CandidateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVerdictIDs(ids...)
}

// AddDecisionIDs adds the "decisions" edge to the TradeDecision entity by IDs.
func (_c *CandidateCreate) AddDecisionIDs(ids ...int) *CandidateCreate {
	_c.mutation.AddDecisionIDs(ids...)
	return _c
}

// AddDecisions adds the "decisions" edges to the TradeDecision entity.
func (_c *CandidateCreate) AddDecisions(v ...*TradeDecision) *CandidateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDecisionIDs(ids...)
}

// AddPositionIDs adds the "positions" edge to the PaperPosition entity by IDs.
func (_c *CandidateCreate) AddPositionIDs(ids ...int) *CandidateCreate {
	_c.mutation.AddPositionIDs(ids...)
	return _c
}

// AddPositions adds the "positions" edges to the PaperPosition entity.
func (_c *CandidateCreate) AddPositions(v ...*PaperPosition) *CandidateCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPositionIDs(ids...)
}

// Mutation returns the CandidateMutation object of the builder.
func (_c *CandidateCreate) Mutation() *CandidateMutation {
	return _c.mutation
}

// Save creates the Candidate in the database.
func (_c *CandidateCreate) Save(ctx context.Context) (*Candidate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CandidateCreate) SaveX(ctx context.Context) *Candidate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CandidateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CandidateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CandidateCreate) defaults() {
	if _, ok := _c.mutation.DiscoveredAt(); !ok {
		v := candidate.DefaultDiscoveredAt()
		_c.mutation.SetDiscoveredAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := candidate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := candidate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CandidateCreate) check() error {
	if _, ok := _c.mutation.Network(); !ok {
		return &ValidationError{Name: "network", err: errors.New(`ent: missing required field "Candidate.network"`)}
	}
	if v, ok := _c.mutation.Network(); ok {
		if err := candidate.NetworkValidator(v); err != nil {
			return &ValidationError{Name: "network", err: fmt.Errorf(`ent: validator failed for field "Candidate.network": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MintAddress(); !ok {
		return &ValidationError{Name: "mint_address", err: errors.New(`ent: missing required field "Candidate.mint_address"`)}
	}
	if v, ok := _c.mutation.MintAddress(); ok {
		if err := candidate.MintAddressValidator(v); err != nil {
			return &ValidationError{Name: "mint_address", err: fmt.Errorf(`ent: validator failed for field "Candidate.mint_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PoolAddress(); !ok {
		return &ValidationError{Name: "pool_address", err: errors.New(`ent: missing required field "Candidate.pool_address"`)}
	}
	if v, ok := _c.mutation.PoolAddress(); ok {
		if err := candidate.PoolAddressValidator(v); err != nil {
			return &ValidationError{Name: "pool_address", err: fmt.Errorf(`ent: validator failed for field "Candidate.pool_address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DiscoveredAt(); !ok {
		return &ValidationError{Name: "discovered_at", err: errors.New(`ent: missing required field "Candidate.discovered_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Candidate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Candidate.updated_at"`)}
	}
	return nil
}

func (_c *CandidateCreate) sqlSave(ctx context.Context) (*Candidate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CandidateCreate) createSpec() (*Candidate, *sqlgraph.CreateSpec) {
	var (
		_node = &Candidate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(candidate.Table, sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Network(); ok {
		_spec.SetField(candidate.FieldNetwork, field.TypeString, value)
		_node.Network = value
	}
	if value, ok := _c.mutation.MintAddress(); ok {
		_spec.SetField(candidate.FieldMintAddress, field.TypeString, value)
		_node.MintAddress = value
	}
	if value, ok := _c.mutation.PoolAddress(); ok {
		_spec.SetField(candidate.FieldPoolAddress, field.TypeString, value)
		_node.PoolAddress = value
	}
	if value, ok := _c.mutation.DiscoveredAt(); ok {
		_spec.SetField(candidate.FieldDiscoveredAt, field.TypeTime, value)
		_node.DiscoveredAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(candidate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(candidate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   candidate.SnapshotsTable,
			Columns: []string{candidate.SnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidatesnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SocialSnapshotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   candidate.SocialSnapshotsTable,
			Columns: []string{candidate.SocialSnapshotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(socialsnapshot.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VerdictsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   candidate.VerdictsTable,
			Columns: []string{candidate.VerdictsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(verdict.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DecisionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   candidate.DecisionsTable,
			Columns: []string{candidate.DecisionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tradedecision.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PositionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   candidate.PositionsTable,
			Columns: []string{candidate.PositionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CandidateCreateBulk is the builder for creating many Candidate entities in bulk.
type CandidateCreateBulk struct {
	config
	err      error
	builders []*CandidateCreate
}

// Save creates the Candidate entities in the database.
func (_c *CandidateCreateBulk) Save(ctx context.Context) ([]*Candidate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Candidate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CandidateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CandidateCreateBulk) SaveX(ctx context.Context) []*Candidate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CandidateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CandidateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
