// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/dailyresult"
)

// DailyResultCreate is the builder for creating a DailyResult entity.
type DailyResultCreate struct {
	config
	mutation *DailyResultMutation
	hooks    []Hook
}

// SetUtcDate sets the "utc_date" field.
func (_c *DailyResultCreate) SetUtcDate(v time.Time) *DailyResultCreate {
	_c.mutation.SetUtcDate(v)
	return _c
}

// SetStrategyVersion sets the "strategy_version" field.
func (_c *DailyResultCreate) SetStrategyVersion(v string) *DailyResultCreate {
	_c.mutation.SetStrategyVersion(v)
	return _c
}

// SetDailyAdmittedCount sets the "daily_admitted_count" field.
func (_c *DailyResultCreate) SetDailyAdmittedCount(v int) *DailyResultCreate {
	_c.mutation.SetDailyAdmittedCount(v)
	return _c
}

// SetRealizedPnlMicros sets the "realized_pnl_micros" field.
func (_c *DailyResultCreate) SetRealizedPnlMicros(v int64) *DailyResultCreate {
	_c.mutation.SetRealizedPnlMicros(v)
	return _c
}

// SetNillableRealizedPnlMicros sets the "realized_pnl_micros" field if the given value is not nil.
func (_c *DailyResultCreate) SetNillableRealizedPnlMicros(v *int64) *DailyResultCreate {
	if v != nil {
		_c.SetRealizedPnlMicros(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DailyResultCreate) SetCreatedAt(v time.Time) *DailyResultCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DailyResultCreate) SetNillableCreatedAt(v *time.Time) *DailyResultCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DailyResultCreate) SetUpdatedAt(v time.Time) *DailyResultCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DailyResultCreate) SetNillableUpdatedAt(v *time.Time) *DailyResultCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the DailyResultMutation object of the builder.
func (_c *DailyResultCreate) Mutation() *DailyResultMutation {
	return _c.mutation
}

// Save creates the DailyResult in the database.
func (_c *DailyResultCreate) Save(ctx context.Context) (*DailyResult, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DailyResultCreate) SaveX(ctx context.Context) *DailyResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyResultCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyResultCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DailyResultCreate) defaults() {
	if _, ok := _c.mutation.RealizedPnlMicros(); !ok {
		v := dailyresult.DefaultRealizedPnlMicros
		_c.mutation.SetRealizedPnlMicros(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dailyresult.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dailyresult.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DailyResultCreate) check() error {
	if _, ok := _c.mutation.UtcDate(); !ok {
		return &ValidationError{Name: "utc_date", err: errors.New(`ent: missing required field "DailyResult.utc_date"`)}
	}
	if _, ok := _c.mutation.StrategyVersion(); !ok {
		return &ValidationError{Name: "strategy_version", err: errors.New(`ent: missing required field "DailyResult.strategy_version"`)}
	}
	if v, ok := _c.mutation.StrategyVersion(); ok {
		if err := dailyresult.StrategyVersionValidator(v); err != nil {
			return &ValidationError{Name: "strategy_version", err: fmt.Errorf(`ent: validator failed for field "DailyResult.strategy_version": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DailyAdmittedCount(); !ok {
		return &ValidationError{Name: "daily_admitted_count", err: errors.New(`ent: missing required field "DailyResult.daily_admitted_count"`)}
	}
	if v, ok := _c.mutation.DailyAdmittedCount(); ok {
		if err := dailyresult.DailyAdmittedCountValidator(v); err != nil {
			return &ValidationError{Name: "daily_admitted_count", err: fmt.Errorf(`ent: validator failed for field "DailyResult.daily_admitted_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RealizedPnlMicros(); !ok {
		return &ValidationError{Name: "realized_pnl_micros", err: errors.New(`ent: missing required field "DailyResult.realized_pnl_micros"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DailyResult.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DailyResult.updated_at"`)}
	}
	return nil
}

func (_c *DailyResultCreate) sqlSave(ctx context.Context) (*DailyResult, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DailyResultCreate) createSpec() (*DailyResult, *sqlgraph.CreateSpec) {
	var (
		_node = &DailyResult{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dailyresult.Table, sqlgraph.NewFieldSpec(dailyresult.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UtcDate(); ok {
		_spec.SetField(dailyresult.FieldUtcDate, field.TypeTime, value)
		_node.UtcDate = value
	}
	if value, ok := _c.mutation.StrategyVersion(); ok {
		_spec.SetField(dailyresult.FieldStrategyVersion, field.TypeString, value)
		_node.StrategyVersion = value
	}
	if value, ok := _c.mutation.DailyAdmittedCount(); ok {
		_spec.SetField(dailyresult.FieldDailyAdmittedCount, field.TypeInt, value)
		_node.DailyAdmittedCount = value
	}
	if value, ok := _c.mutation.RealizedPnlMicros(); ok {
		_spec.SetField(dailyresult.FieldRealizedPnlMicros, field.TypeInt64, value)
		_node.RealizedPnlMicros = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dailyresult.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dailyresult.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DailyResultCreateBulk is the builder for creating many DailyResult entities in bulk.
type DailyResultCreateBulk struct {
	config
	err      error
	builders []*DailyResultCreate
}

// Save creates the DailyResult entities in the database.
func (_c *DailyResultCreateBulk) Save(ctx context.Context) ([]*DailyResult, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DailyResult, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DailyResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DailyResultCreateBulk) SaveX(ctx context.Context) []*DailyResult {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyResultCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyResultCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
