// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/positionevent"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/positionmark"
)

// PaperPositionCreate is the builder for creating a PaperPosition entity.
type PaperPositionCreate struct {
	config
	mutation *PaperPositionMutation
	hooks    []Hook
}

// SetState sets the "state" field.
func (_c *PaperPositionCreate) SetState(v paperposition.State) *PaperPositionCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNotionalMicros sets the "notional_micros" field.
func (_c *PaperPositionCreate) SetNotionalMicros(v int64) *PaperPositionCreate {
	_c.mutation.SetNotionalMicros(v)
	return _c
}

// SetEntryPrice sets the "entry_price" field.
func (_c *PaperPositionCreate) SetEntryPrice(v string) *PaperPositionCreate {
	_c.mutation.SetEntryPrice(v)
	return _c
}

// SetTokenQuantity sets the "token_quantity" field.
func (_c *PaperPositionCreate) SetTokenQuantity(v string) *PaperPositionCreate {
	_c.mutation.SetTokenQuantity(v)
	return _c
}

// SetOpenedAt sets the "opened_at" field.
func (_c *PaperPositionCreate) SetOpenedAt(v time.Time) *PaperPositionCreate {
	_c.mutation.SetOpenedAt(v)
	return _c
}

// SetNillableOpenedAt sets the "opened_at" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableOpenedAt(v *time.Time) *PaperPositionCreate {
	if v != nil {
		_c.SetOpenedAt(*v)
	}
	return _c
}

// SetClosedAt sets the "closed_at" field.
func (_c *PaperPositionCreate) SetClosedAt(v time.Time) *PaperPositionCreate {
	_c.mutation.SetClosedAt(v)
	return _c
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableClosedAt(v *time.Time) *PaperPositionCreate {
	if v != nil {
		_c.SetClosedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaperPositionCreate) SetCreatedAt(v time.Time) *PaperPositionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableCreatedAt(v *time.Time) *PaperPositionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaperPositionCreate) SetUpdatedAt(v time.Time) *PaperPositionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaperPositionCreate) SetNillableUpdatedAt(v *time.Time) *PaperPositionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_c *PaperPositionCreate) SetCandidateID(id int) *PaperPositionCreate {
	_c.mutation.SetCandidateID(id)
	return _c
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_c *PaperPositionCreate) SetCandidate(v *Candidate) *PaperPositionCreate {
	return _c.SetCandidateID(v.ID)
}

// AddMarkIDs adds the "marks" edge to the PositionMark entity by IDs.
func (_c *PaperPositionCreate) AddMarkIDs(ids ...int) *PaperPositionCreate {
	_c.mutation.AddMarkIDs(ids...)
	return _c
}

// AddMarks adds the "marks" edges to the PositionMark entity.
func (_c *PaperPositionCreate) AddMarks(v ...*PositionMark) *PaperPositionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMarkIDs(ids...)
}

// AddEventIDs adds the "events" edge to the PositionEvent entity by IDs.
func (_c *PaperPositionCreate) AddEventIDs(ids ...int) *PaperPositionCreate {
	_c.mutation.AddEventIDs(ids...)
	return _c
}

// AddEvents adds the "events" edges to the PositionEvent entity.
func (_c *PaperPositionCreate) AddEvents(v ...*PositionEvent) *PaperPositionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEventIDs(ids...)
}

// Mutation returns the PaperPositionMutation object of the builder.
func (_c *PaperPositionCreate) Mutation() *PaperPositionMutation {
	return _c.mutation
}

// Save creates the PaperPosition in the database.
func (_c *PaperPositionCreate) Save(ctx context.Context) (*PaperPosition, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaperPositionCreate) SaveX(ctx context.Context) *PaperPosition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaperPositionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaperPositionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaperPositionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paperposition.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paperposition.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaperPositionCreate) check() error {
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "PaperPosition.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := paperposition.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NotionalMicros(); !ok {
		return &ValidationError{Name: "notional_micros", err: errors.New(`ent: missing required field "PaperPosition.notional_micros"`)}
	}
	if v, ok := _c.mutation.NotionalMicros(); ok {
		if err := paperposition.NotionalMicrosValidator(v); err != nil {
			return &ValidationError{Name: "notional_micros", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.notional_micros": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EntryPrice(); !ok {
		return &ValidationError{Name: "entry_price", err: errors.New(`ent: missing required field "PaperPosition.entry_price"`)}
	}
	if v, ok := _c.mutation.EntryPrice(); ok {
		if err := paperposition.EntryPriceValidator(v); err != nil {
			return &ValidationError{Name: "entry_price", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.entry_price": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenQuantity(); !ok {
		return &ValidationError{Name: "token_quantity", err: errors.New(`ent: missing required field "PaperPosition.token_quantity"`)}
	}
	if v, ok := _c.mutation.TokenQuantity(); ok {
		if err := paperposition.TokenQuantityValidator(v); err != nil {
			return &ValidationError{Name: "token_quantity", err: fmt.Errorf(`ent: validator failed for field "PaperPosition.token_quantity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaperPosition.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaperPosition.updated_at"`)}
	}
	if len(_c.mutation.CandidateIDs()) == 0 {
		return &ValidationError{Name: "candidate", err: errors.New(`ent: missing required edge "PaperPosition.candidate"`)}
	}
	return nil
}

func (_c *PaperPositionCreate) sqlSave(ctx context.Context) (*PaperPosition, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaperPositionCreate) createSpec() (*PaperPosition, *sqlgraph.CreateSpec) {
	var (
		_node = &PaperPosition{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paperposition.Table, sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(paperposition.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.NotionalMicros(); ok {
		_spec.SetField(paperposition.FieldNotionalMicros, field.TypeInt64, value)
		_node.NotionalMicros = value
	}
	if value, ok := _c.mutation.EntryPrice(); ok {
		_spec.SetField(paperposition.FieldEntryPrice, field.TypeString, value)
		_node.EntryPrice = value
	}
	if value, ok := _c.mutation.TokenQuantity(); ok {
		_spec.SetField(paperposition.FieldTokenQuantity, field.TypeString, value)
		_node.TokenQuantity = value
	}
	if value, ok := _c.mutation.OpenedAt(); ok {
		_spec.SetField(paperposition.FieldOpenedAt, field.TypeTime, value)
		_node.OpenedAt = &value
	}
	if value, ok := _c.mutation.ClosedAt(); ok {
		_spec.SetField(paperposition.FieldClosedAt, field.TypeTime, value)
		_node.ClosedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paperposition.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paperposition.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paperposition.CandidateTable,
			Columns: []string{paperposition.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.candidate_positions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MarksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.MarksTable,
			Columns: []string{paperposition.MarksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   paperposition.EventsTable,
			Columns: []string{paperposition.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(positionevent.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PaperPositionCreateBulk is the builder for creating many PaperPosition entities in bulk.
type PaperPositionCreateBulk struct {
	config
	err      error
	builders []*PaperPositionCreate
}

// Save creates the PaperPosition entities in the database.
func (_c *PaperPositionCreateBulk) Save(ctx context.Context) ([]*PaperPosition, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaperPosition, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaperPositionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaperPositionCreateBulk) SaveX(ctx context.Context) []*PaperPosition {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaperPositionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaperPositionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
