// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/paperposition"
)

// PaperPosition is the model entity for the PaperPosition schema.
type PaperPosition struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// State holds the value of the "state" field.
	State paperposition.State `json:"state,omitempty"`
	// NotionalMicros holds the value of the "notional_micros" field.
	NotionalMicros int64 `json:"notional_micros,omitempty"`
	// EntryPrice holds the value of the "entry_price" field.
	EntryPrice string `json:"entry_price,omitempty"`
	// TokenQuantity holds the value of the "token_quantity" field.
	TokenQuantity string `json:"token_quantity,omitempty"`
	// OpenedAt holds the value of the "opened_at" field.
	OpenedAt *time.Time `json:"opened_at,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaperPositionQuery when eager-loading is set.
	Edges               PaperPositionEdges `json:"edges"`
	candidate_positions *int
	selectValues        sql.SelectValues
}

// PaperPositionEdges holds the relations/edges for other nodes in the graph.
type PaperPositionEdges struct {
	// Candidate holds the value of the candidate edge.
	Candidate *Candidate `json:"candidate,omitempty"`
	// Marks holds the value of the marks edge.
	Marks []*PositionMark `json:"marks,omitempty"`
	// Events holds the value of the events edge.
	Events []*PositionEvent `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CandidateOrErr returns the Candidate value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaperPositionEdges) CandidateOrErr() (*Candidate, error) {
	if e.Candidate != nil {
		return e.Candidate, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: candidate.Label}
	}
	return nil, &NotLoadedError{edge: "candidate"}
}

// MarksOrErr returns the Marks value or an error if the edge
// was not loaded in eager-loading.
func (e PaperPositionEdges) MarksOrErr() ([]*PositionMark, error) {
	if e.loadedTypes[1] {
		return e.Marks, nil
	}
	return nil, &NotLoadedError{edge: "marks"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e PaperPositionEdges) EventsOrErr() ([]*PositionEvent, error) {
	if e.loadedTypes[2] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaperPosition) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paperposition.FieldID, paperposition.FieldNotionalMicros:
			values[i] = new(sql.NullInt64)
		case paperposition.FieldState, paperposition.FieldEntryPrice, paperposition.FieldTokenQuantity:
			values[i] = new(sql.NullString)
		case paperposition.FieldOpenedAt, paperposition.FieldClosedAt, paperposition.FieldCreatedAt, paperposition.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case paperposition.ForeignKeys[0]: // candidate_positions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaperPosition fields.
func (_m *PaperPosition) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paperposition.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case paperposition.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = paperposition.State(value.String)
			}
		case paperposition.FieldNotionalMicros:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field notional_micros", values[i])
			} else if value.Valid {
				_m.NotionalMicros = value.Int64
			}
		case paperposition.FieldEntryPrice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_price", values[i])
			} else if value.Valid {
				_m.EntryPrice = value.String
			}
		case paperposition.FieldTokenQuantity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token_quantity", values[i])
			} else if value.Valid {
				_m.TokenQuantity = value.String
			}
		case paperposition.FieldOpenedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field opened_at", values[i])
			} else if value.Valid {
				_m.OpenedAt = new(time.Time)
				*_m.OpenedAt = value.Time
			}
		case paperposition.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case paperposition.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case paperposition.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case paperposition.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field candidate_positions", value)
			} else if value.Valid {
				_m.candidate_positions = new(int)
				*_m.candidate_positions = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaperPosition.
// This includes values selected through modifiers, order, etc.
func (_m *PaperPosition) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCandidate queries the "candidate" edge of the PaperPosition entity.
func (_m *PaperPosition) QueryCandidate() *CandidateQuery {
	return NewPaperPositionClient(_m.config).QueryCandidate(_m)
}

// QueryMarks queries the "marks" edge of the PaperPosition entity.
func (_m *PaperPosition) QueryMarks() *PositionMarkQuery {
	return NewPaperPositionClient(_m.config).QueryMarks(_m)
}

// QueryEvents queries the "events" edge of the PaperPosition entity.
func (_m *PaperPosition) QueryEvents() *PositionEventQuery {
	return NewPaperPositionClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this PaperPosition.
// Note that you need to call PaperPosition.Unwrap() before calling this method if this PaperPosition
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaperPosition) Update() *PaperPositionUpdateOne {
	return NewPaperPositionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaperPosition entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaperPosition) Unwrap() *PaperPosition {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaperPosition is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaperPosition) String() string {
	var builder strings.Builder
	builder.WriteString("PaperPosition(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", _m.State))
	builder.WriteString(", ")
	builder.WriteString("notional_micros=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotionalMicros))
	builder.WriteString(", ")
	builder.WriteString("entry_price=")
	builder.WriteString(_m.EntryPrice)
	builder.WriteString(", ")
	builder.WriteString("token_quantity=")
	builder.WriteString(_m.TokenQuantity)
	builder.WriteString(", ")
	if v := _m.OpenedAt; v != nil {
		builder.WriteString("opened_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaperPositions is a parsable slice of PaperPosition.
type PaperPositions []*PaperPosition
