// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/positionmark"
)

// PositionMarkCreate is the builder for creating a PositionMark entity.
type PositionMarkCreate struct {
	config
	mutation *PositionMarkMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPrice sets the "price" field.
func (_c *PositionMarkCreate) SetPrice(v string) *PositionMarkCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetObservedAt sets the "observed_at" field.
func (_c *PositionMarkCreate) SetObservedAt(v time.Time) *PositionMarkCreate {
	_c.mutation.SetObservedAt(v)
	return _c
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_c *PositionMarkCreate) SetNillableObservedAt(v *time.Time) *PositionMarkCreate {
	if v != nil {
		_c.SetObservedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PositionMarkCreate) SetCreatedAt(v time.Time) *PositionMarkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PositionMarkCreate) SetNillableCreatedAt(v *time.Time) *PositionMarkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPositionID sets the "position" edge to the PaperPosition entity by ID.
func (_c *PositionMarkCreate) SetPositionID(id int) *PositionMarkCreate {
	_c.mutation.SetPositionID(id)
	return _c
}

// SetPosition sets the "position" edge to the PaperPosition entity.
func (_c *PositionMarkCreate) SetPosition(v *PaperPosition) *PositionMarkCreate {
	return _c.SetPositionID(v.ID)
}

// Mutation returns the PositionMarkMutation object of the builder.
func (_c *PositionMarkCreate) Mutation() *PositionMarkMutation {
	return _c.mutation
}

// Save creates the PositionMark in the database.
func (_c *PositionMarkCreate) Save(ctx context.Context) (*PositionMark, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PositionMarkCreate) SaveX(ctx context.Context) *PositionMark {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PositionMarkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PositionMarkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PositionMarkCreate) defaults() {
	if _, ok := _c.mutation.ObservedAt(); !ok {
		v := positionmark.DefaultObservedAt()
		_c.mutation.SetObservedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := positionmark.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PositionMarkCreate) check() error {
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "PositionMark.price"`)}
	}
	if v, ok := _c.mutation.Price(); ok {
		if err := positionmark.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "PositionMark.price": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObservedAt(); !ok {
		return &ValidationError{Name: "observed_at", err: errors.New(`ent: missing required field "PositionMark.observed_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PositionMark.created_at"`)}
	}
	if len(_c.mutation.PositionIDs()) == 0 {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required edge "PositionMark.position"`)}
	}
	return nil
}

func (_c *PositionMarkCreate) sqlSave(ctx context.Context) (*PositionMark, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PositionMarkCreate) createSpec() (*PositionMark, *sqlgraph.CreateSpec) {
	var (
		_node = &PositionMark{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(positionmark.Table, sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(positionmark.FieldPrice, field.TypeString, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.ObservedAt(); ok {
		_spec.SetField(positionmark.FieldObservedAt, field.TypeTime, value)
		_node.ObservedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(positionmark.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionmark.PositionTable,
			Columns: []string{positionmark.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.paper_position_marks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PositionMark.Create().
//		SetPrice(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PositionMarkUpsert) {
//			SetPrice(v+v).
//		}).
//		Exec(ctx)
func (_c *PositionMarkCreate) OnConflict(opts ...sql.ConflictOption) *PositionMarkUpsertOne {
	_c.conflict = opts
	return &PositionMarkUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PositionMark.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PositionMarkCreate) OnConflictColumns(columns ...string) *PositionMarkUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PositionMarkUpsertOne{
		create: _c,
	}
}

type (
	// PositionMarkUpsertOne is the builder for "upsert"-ing
	//  one PositionMark node.
	PositionMarkUpsertOne struct {
		create *PositionMarkCreate
	}

	// PositionMarkUpsert is the "OnConflict" setter.
	PositionMarkUpsert struct {
		*sql.UpdateSet
	}
)

// SetPrice sets the "price" field.
func (u *PositionMarkUpsert) SetPrice(v string) *PositionMarkUpsert {
	u.Set(positionmark.FieldPrice, v)
	return u
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PositionMarkUpsert) UpdatePrice() *PositionMarkUpsert {
	u.SetExcluded(positionmark.FieldPrice)
	return u
}

// SetObservedAt sets the "observed_at" field.
func (u *PositionMarkUpsert) SetObservedAt(v time.Time) *PositionMarkUpsert {
	u.Set(positionmark.FieldObservedAt, v)
	return u
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *PositionMarkUpsert) UpdateObservedAt() *PositionMarkUpsert {
	u.SetExcluded(positionmark.FieldObservedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PositionMark.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PositionMarkUpsertOne) UpdateNewValues() *PositionMarkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(positionmark.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PositionMark.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PositionMarkUpsertOne) Ignore() *PositionMarkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PositionMarkUpsertOne) DoNothing() *PositionMarkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PositionMarkCreate.OnConflict
// documentation for more info.
func (u *PositionMarkUpsertOne) Update(set func(*PositionMarkUpsert)) *PositionMarkUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PositionMarkUpsert{UpdateSet: update})
	}))
	return u
}

// SetPrice sets the "price" field.
func (u *PositionMarkUpsertOne) SetPrice(v string) *PositionMarkUpsertOne {
	return u.Update(func(s *PositionMarkUpsert) {
		s.SetPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PositionMarkUpsertOne) UpdatePrice() *PositionMarkUpsertOne {
	return u.Update(func(s *PositionMarkUpsert) {
		s.UpdatePrice()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *PositionMarkUpsertOne) SetObservedAt(v time.Time) *PositionMarkUpsertOne {
	return u.Update(func(s *PositionMarkUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *PositionMarkUpsertOne) UpdateObservedAt() *PositionMarkUpsertOne {
	return u.Update(func(s *PositionMarkUpsert) {
		s.UpdateObservedAt()
	})
}

// Exec executes the query.
func (u *PositionMarkUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PositionMarkCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PositionMarkUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PositionMarkUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PositionMarkUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PositionMarkCreateBulk is the builder for creating many PositionMark entities in bulk.
type PositionMarkCreateBulk struct {
	config
	err      error
	builders []*PositionMarkCreate
	conflict []sql.ConflictOption
}

// Save creates the PositionMark entities in the database.
func (_c *PositionMarkCreateBulk) Save(ctx context.Context) ([]*PositionMark, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PositionMark, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PositionMarkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PositionMarkCreateBulk) SaveX(ctx context.Context) []*PositionMark {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PositionMarkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PositionMarkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PositionMark.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PositionMarkUpsert) {
//			SetPrice(v+v).
//		}).
//		Exec(ctx)
func (_c *PositionMarkCreateBulk) OnConflict(opts ...sql.ConflictOption) *PositionMarkUpsertBulk {
	_c.conflict = opts
	return &PositionMarkUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PositionMark.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PositionMarkCreateBulk) OnConflictColumns(columns ...string) *PositionMarkUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PositionMarkUpsertBulk{
		create: _c,
	}
}

// PositionMarkUpsertBulk is the builder for "upsert"-ing
// a bulk of PositionMark nodes.
type PositionMarkUpsertBulk struct {
	create *PositionMarkCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PositionMark.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PositionMarkUpsertBulk) UpdateNewValues() *PositionMarkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(positionmark.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PositionMark.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PositionMarkUpsertBulk) Ignore() *PositionMarkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PositionMarkUpsertBulk) DoNothing() *PositionMarkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PositionMarkCreateBulk.OnConflict
// documentation for more info.
func (u *PositionMarkUpsertBulk) Update(set func(*PositionMarkUpsert)) *PositionMarkUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PositionMarkUpsert{UpdateSet: update})
	}))
	return u
}

// SetPrice sets the "price" field.
func (u *PositionMarkUpsertBulk) SetPrice(v string) *PositionMarkUpsertBulk {
	return u.Update(func(s *PositionMarkUpsert) {
		s.SetPrice(v)
	})
}

// UpdatePrice sets the "price" field to the value that was provided on create.
func (u *PositionMarkUpsertBulk) UpdatePrice() *PositionMarkUpsertBulk {
	return u.Update(func(s *PositionMarkUpsert) {
		s.UpdatePrice()
	})
}

// SetObservedAt sets the "observed_at" field.
func (u *PositionMarkUpsertBulk) SetObservedAt(v time.Time) *PositionMarkUpsertBulk {
	return u.Update(func(s *PositionMarkUpsert) {
		s.SetObservedAt(v)
	})
}

// UpdateObservedAt sets the "observed_at" field to the value that was provided on create.
func (u *PositionMarkUpsertBulk) UpdateObservedAt() *PositionMarkUpsertBulk {
	return u.Update(func(s *PositionMarkUpsert) {
		s.UpdateObservedAt()
	})
}

// Exec executes the query.
func (u *PositionMarkUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PositionMarkCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PositionMarkCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PositionMarkUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
