// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/positionmark"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/predicate"
)

// PositionMarkUpdate is the builder for updating PositionMark entities.
type PositionMarkUpdate struct {
	config
	hooks    []Hook
	mutation *PositionMarkMutation
}

// Where appends a list predicates to the PositionMarkUpdate builder.
func (_u *PositionMarkUpdate) Where(ps ...predicate.PositionMark) *PositionMarkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPrice sets the "price" field.
func (_u *PositionMarkUpdate) SetPrice(v string) *PositionMarkUpdate {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PositionMarkUpdate) SetNillablePrice(v *string) *PositionMarkUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *PositionMarkUpdate) SetObservedAt(v time.Time) *PositionMarkUpdate {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *PositionMarkUpdate) SetNillableObservedAt(v *time.Time) *PositionMarkUpdate {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// SetPositionID sets the "position" edge to the PaperPosition entity by ID.
func (_u *PositionMarkUpdate) SetPositionID(id int) *PositionMarkUpdate {
	_u.mutation.SetPositionID(id)
	return _u
}

// SetPosition sets the "position" edge to the PaperPosition entity.
func (_u *PositionMarkUpdate) SetPosition(v *PaperPosition) *PositionMarkUpdate {
	return _u.SetPositionID(v.ID)
}

// Mutation returns the PositionMarkMutation object of the builder.
func (_u *PositionMarkUpdate) Mutation() *PositionMarkMutation {
	return _u.mutation
}

// ClearPosition clears the "position" edge to the PaperPosition entity.
func (_u *PositionMarkUpdate) ClearPosition() *PositionMarkUpdate {
	_u.mutation.ClearPosition()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PositionMarkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PositionMarkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PositionMarkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PositionMarkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PositionMarkUpdate) check() error {
	if v, ok := _u.mutation.Price(); ok {
		if err := positionmark.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "PositionMark.price": %w`, err)}
		}
	}
	if _u.mutation.PositionCleared() && len(_u.mutation.PositionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PositionMark.position"`)
	}
	return nil
}

func (_u *PositionMarkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(positionmark.Table, positionmark.Columns, sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(positionmark.FieldPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(positionmark.FieldObservedAt, field.TypeTime, value)
	}
	if _u.mutation.PositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionmark.PositionTable,
			Columns: []string{positionmark.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionmark.PositionTable,
			Columns: []string{positionmark.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{positionmark.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PositionMarkUpdateOne is the builder for updating a single PositionMark entity.
type PositionMarkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PositionMarkMutation
}

// SetPrice sets the "price" field.
func (_u *PositionMarkUpdateOne) SetPrice(v string) *PositionMarkUpdateOne {
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PositionMarkUpdateOne) SetNillablePrice(v *string) *PositionMarkUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// SetObservedAt sets the "observed_at" field.
func (_u *PositionMarkUpdateOne) SetObservedAt(v time.Time) *PositionMarkUpdateOne {
	_u.mutation.SetObservedAt(v)
	return _u
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_u *PositionMarkUpdateOne) SetNillableObservedAt(v *time.Time) *PositionMarkUpdateOne {
	if v != nil {
		_u.SetObservedAt(*v)
	}
	return _u
}

// SetPositionID sets the "position" edge to the PaperPosition entity by ID.
func (_u *PositionMarkUpdateOne) SetPositionID(id int) *PositionMarkUpdateOne {
	_u.mutation.SetPositionID(id)
	return _u
}

// SetPosition sets the "position" edge to the PaperPosition entity.
func (_u *PositionMarkUpdateOne) SetPosition(v *PaperPosition) *PositionMarkUpdateOne {
	return _u.SetPositionID(v.ID)
}

// Mutation returns the PositionMarkMutation object of the builder.
func (_u *PositionMarkUpdateOne) Mutation() *PositionMarkMutation {
	return _u.mutation
}

// ClearPosition clears the "position" edge to the PaperPosition entity.
func (_u *PositionMarkUpdateOne) ClearPosition() *PositionMarkUpdateOne {
	_u.mutation.ClearPosition()
	return _u
}

// Where appends a list predicates to the PositionMarkUpdate builder.
func (_u *PositionMarkUpdateOne) Where(ps ...predicate.PositionMark) *PositionMarkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PositionMarkUpdateOne) Select(field string, fields ...string) *PositionMarkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PositionMark entity.
func (_u *PositionMarkUpdateOne) Save(ctx context.Context) (*PositionMark, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PositionMarkUpdateOne) SaveX(ctx context.Context) *PositionMark {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PositionMarkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PositionMarkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PositionMarkUpdateOne) check() error {
	if v, ok := _u.mutation.Price(); ok {
		if err := positionmark.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "PositionMark.price": %w`, err)}
		}
	}
	if _u.mutation.PositionCleared() && len(_u.mutation.PositionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PositionMark.position"`)
	}
	return nil
}

func (_u *PositionMarkUpdateOne) sqlSave(ctx context.Context) (_node *PositionMark, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(positionmark.Table, positionmark.Columns, sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PositionMark.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, positionmark.FieldID)
		for _, f := range fields {
			if !positionmark.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != positionmark.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(positionmark.FieldPrice, field.TypeString, value)
	}
	if value, ok := _u.mutation.ObservedAt(); ok {
		_spec.SetField(positionmark.FieldObservedAt, field.TypeTime, value)
	}
	if _u.mutation.PositionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionmark.PositionTable,
			Columns: []string{positionmark.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionmark.PositionTable,
			Columns: []string{positionmark.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PositionMark{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{positionmark.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
