// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/positionmark"
)

// PositionMarkCreate is the builder for creating a PositionMark entity.
type PositionMarkCreate struct {
	config
	mutation *PositionMarkMutation
	hooks    []Hook
}

// SetPrice sets the "price" field.
func (_c *PositionMarkCreate) SetPrice(v string) *PositionMarkCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetObservedAt sets the "observed_at" field.
func (_c *PositionMarkCreate) SetObservedAt(v time.Time) *PositionMarkCreate {
	_c.mutation.SetObservedAt(v)
	return _c
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_c *PositionMarkCreate) SetNillableObservedAt(v *time.Time) *PositionMarkCreate {
	if v != nil {
		_c.SetObservedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PositionMarkCreate) SetCreatedAt(v time.Time) *PositionMarkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PositionMarkCreate) SetNillableCreatedAt(v *time.Time) *PositionMarkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPositionID sets the "position" edge to the PaperPosition entity by ID.
func (_c *PositionMarkCreate) SetPositionID(id int) *PositionMarkCreate {
	_c.mutation.SetPositionID(id)
	return _c
}

// SetPosition sets the "position" edge to the PaperPosition entity.
func (_c *PositionMarkCreate) SetPosition(v *PaperPosition) *PositionMarkCreate {
	return _c.SetPositionID(v.ID)
}

// Mutation returns the PositionMarkMutation object of the builder.
func (_c *PositionMarkCreate) Mutation() *PositionMarkMutation {
	return _c.mutation
}

// Save creates the PositionMark in the database.
func (_c *PositionMarkCreate) Save(ctx context.Context) (*PositionMark, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PositionMarkCreate) SaveX(ctx context.Context) *PositionMark {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PositionMarkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PositionMarkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PositionMarkCreate) defaults() {
	if _, ok := _c.mutation.ObservedAt(); !ok {
		v := positionmark.DefaultObservedAt()
		_c.mutation.SetObservedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := positionmark.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PositionMarkCreate) check() error {
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "PositionMark.price"`)}
	}
	if v, ok := _c.mutation.Price(); ok {
		if err := positionmark.PriceValidator(v); err != nil {
			return &ValidationError{Name: "price", err: fmt.Errorf(`ent: validator failed for field "PositionMark.price": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ObservedAt(); !ok {
		return &ValidationError{Name: "observed_at", err: errors.New(`ent: missing required field "PositionMark.observed_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PositionMark.created_at"`)}
	}
	if len(_c.mutation.PositionIDs()) == 0 {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required edge "PositionMark.position"`)}
	}
	return nil
}

func (_c *PositionMarkCreate) sqlSave(ctx context.Context) (*PositionMark, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PositionMarkCreate) createSpec() (*PositionMark, *sqlgraph.CreateSpec) {
	var (
		_node = &PositionMark{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(positionmark.Table, sqlgraph.NewFieldSpec(positionmark.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(positionmark.FieldPrice, field.TypeString, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.ObservedAt(); ok {
		_spec.SetField(positionmark.FieldObservedAt, field.TypeTime, value)
		_node.ObservedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(positionmark.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionmark.PositionTable,
			Columns: []string{positionmark.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.paper_position_marks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PositionMarkCreateBulk is the builder for creating many PositionMark entities in bulk.
type PositionMarkCreateBulk struct {
	config
	err      error
	builders []*PositionMarkCreate
}

// Save creates the PositionMark entities in the database.
func (_c *PositionMarkCreateBulk) Save(ctx context.Context) ([]*PositionMark, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PositionMark, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PositionMarkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PositionMarkCreateBulk) SaveX(ctx context.Context) []*PositionMark {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PositionMarkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PositionMarkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
