// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/positionevent"
)

// PositionEventCreate is the builder for creating a PositionEvent entity.
type PositionEventCreate struct {
	config
	mutation *PositionEventMutation
	hooks    []Hook
}

// SetEventType sets the "event_type" field.
func (_c *PositionEventCreate) SetEventType(v string) *PositionEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetDetails sets the "details" field.
func (_c *PositionEventCreate) SetDetails(v map[string]interface{}) *PositionEventCreate {
	_c.mutation.SetDetails(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PositionEventCreate) SetCreatedAt(v time.Time) *PositionEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PositionEventCreate) SetNillableCreatedAt(v *time.Time) *PositionEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPositionID sets the "position" edge to the PaperPosition entity by ID.
func (_c *PositionEventCreate) SetPositionID(id int) *PositionEventCreate {
	_c.mutation.SetPositionID(id)
	return _c
}

// SetPosition sets the "position" edge to the PaperPosition entity.
func (_c *PositionEventCreate) SetPosition(v *PaperPosition) *PositionEventCreate {
	return _c.SetPositionID(v.ID)
}

// Mutation returns the PositionEventMutation object of the builder.
func (_c *PositionEventCreate) Mutation() *PositionEventMutation {
	return _c.mutation
}

// Save creates the PositionEvent in the database.
func (_c *PositionEventCreate) Save(ctx context.Context) (*PositionEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PositionEventCreate) SaveX(ctx context.Context) *PositionEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PositionEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PositionEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PositionEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := positionevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PositionEventCreate) check() error {
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "PositionEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := positionevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "PositionEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Details(); !ok {
		return &ValidationError{Name: "details", err: errors.New(`ent: missing required field "PositionEvent.details"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PositionEvent.created_at"`)}
	}
	if len(_c.mutation.PositionIDs()) == 0 {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required edge "PositionEvent.position"`)}
	}
	return nil
}

func (_c *PositionEventCreate) sqlSave(ctx context.Context) (*PositionEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PositionEventCreate) createSpec() (*PositionEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &PositionEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(positionevent.Table, sqlgraph.NewFieldSpec(positionevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(positionevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Details(); ok {
		_spec.SetField(positionevent.FieldDetails, field.TypeJSON, value)
		_node.Details = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(positionevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.PositionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   positionevent.PositionTable,
			Columns: []string{positionevent.PositionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paperposition.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.paper_position_events = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PositionEventCreateBulk is the builder for creating many PositionEvent entities in bulk.
type PositionEventCreateBulk struct {
	config
	err      error
	builders []*PositionEventCreate
}

// Save creates the PositionEvent entities in the database.
func (_c *PositionEventCreateBulk) Save(ctx context.Context) ([]*PositionEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PositionEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PositionEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PositionEventCreateBulk) SaveX(ctx context.Context) []*PositionEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PositionEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PositionEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
