// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/paperposition"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/positionmark"
)

// PositionMark is the model entity for the PositionMark schema.
type PositionMark struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Price holds the value of the "price" field.
	Price string `json:"price,omitempty"`
	// ObservedAt holds the value of the "observed_at" field.
	ObservedAt time.Time `json:"observed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PositionMarkQuery when eager-loading is set.
	Edges                PositionMarkEdges `json:"edges"`
	paper_position_marks *int
	selectValues         sql.SelectValues
}

// PositionMarkEdges holds the relations/edges for other nodes in the graph.
type PositionMarkEdges struct {
	// Position holds the value of the position edge.
	Position *PaperPosition `json:"position,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PositionOrErr returns the Position value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PositionMarkEdges) PositionOrErr() (*PaperPosition, error) {
	if e.Position != nil {
		return e.Position, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: paperposition.Label}
	}
	return nil, &NotLoadedError{edge: "position"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PositionMark) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case positionmark.FieldID:
			values[i] = new(sql.NullInt64)
		case positionmark.FieldPrice:
			values[i] = new(sql.NullString)
		case positionmark.FieldObservedAt, positionmark.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case positionmark.ForeignKeys[0]: // paper_position_marks
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PositionMark fields.
func (_m *PositionMark) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case positionmark.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case positionmark.FieldPrice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.String
			}
		case positionmark.FieldObservedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field observed_at", values[i])
			} else if value.Valid {
				_m.ObservedAt = value.Time
			}
		case positionmark.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case positionmark.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field paper_position_marks", value)
			} else if value.Valid {
				_m.paper_position_marks = new(int)
				*_m.paper_position_marks = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PositionMark.
// This includes values selected through modifiers, order, etc.
func (_m *PositionMark) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPosition queries the "position" edge of the PositionMark entity.
func (_m *PositionMark) QueryPosition() *PaperPositionQuery {
	return NewPositionMarkClient(_m.config).QueryPosition(_m)
}

// Update returns a builder for updating this PositionMark.
// Note that you need to call PositionMark.Unwrap() before calling this method if this PositionMark
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PositionMark) Update() *PositionMarkUpdateOne {
	return NewPositionMarkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PositionMark entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PositionMark) Unwrap() *PositionMark {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PositionMark is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PositionMark) String() string {
	var builder strings.Builder
	builder.WriteString("PositionMark(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("price=")
	builder.WriteString(_m.Price)
	builder.WriteString(", ")
	builder.WriteString("observed_at=")
	builder.WriteString(_m.ObservedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PositionMarks is a parsable slice of PositionMark.
type PositionMarks []*PositionMark
