// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/socialsnapshot"
)

// SocialSnapshotCreate is the builder for creating a SocialSnapshot entity.
type SocialSnapshotCreate struct {
	config
	mutation *SocialSnapshotMutation
	hooks    []Hook
}

// SetSocialEvidence sets the "social_evidence" field.
func (_c *SocialSnapshotCreate) SetSocialEvidence(v map[string]interface{}) *SocialSnapshotCreate {
	_c.mutation.SetSocialEvidence(v)
	return _c
}

// SetScore sets the "score" field.
func (_c *SocialSnapshotCreate) SetScore(v int) *SocialSnapshotCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetObservedAt sets the "observed_at" field.
func (_c *SocialSnapshotCreate) SetObservedAt(v time.Time) *SocialSnapshotCreate {
	_c.mutation.SetObservedAt(v)
	return _c
}

// SetNillableObservedAt sets the "observed_at" field if the given value is not nil.
func (_c *SocialSnapshotCreate) SetNillableObservedAt(v *time.Time) *SocialSnapshotCreate {
	if v != nil {
		_c.SetObservedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SocialSnapshotCreate) SetCreatedAt(v time.Time) *SocialSnapshotCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SocialSnapshotCreate) SetNillableCreatedAt(v *time.Time) *SocialSnapshotCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_c *SocialSnapshotCreate) SetCandidateID(id int) *SocialSnapshotCreate {
	_c.mutation.SetCandidateID(id)
	return _c
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_c *SocialSnapshotCreate) SetCandidate(v *Candidate) *SocialSnapshotCreate {
	return _c.SetCandidateID(v.ID)
}

// Mutation returns the SocialSnapshotMutation object of the builder.
func (_c *SocialSnapshotCreate) Mutation() *SocialSnapshotMutation {
	return _c.mutation
}

// Save creates the SocialSnapshot in the database.
func (_c *SocialSnapshotCreate) Save(ctx context.Context) (*SocialSnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SocialSnapshotCreate) SaveX(ctx context.Context) *SocialSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SocialSnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SocialSnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SocialSnapshotCreate) defaults() {
	if _, ok := _c.mutation.ObservedAt(); !ok {
		v := socialsnapshot.DefaultObservedAt()
		_c.mutation.SetObservedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := socialsnapshot.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SocialSnapshotCreate) check() error {
	if _, ok := _c.mutation.SocialEvidence(); !ok {
		return &ValidationError{Name: "social_evidence", err: errors.New(`ent: missing required field "SocialSnapshot.social_evidence"`)}
	}
	if _, ok := _c.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "SocialSnapshot.score"`)}
	}
	if _, ok := _c.mutation.ObservedAt(); !ok {
		return &ValidationError{Name: "observed_at", err: errors.New(`ent: missing required field "SocialSnapshot.observed_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SocialSnapshot.created_at"`)}
	}
	if len(_c.mutation.CandidateIDs()) == 0 {
		return &ValidationError{Name: "candidate", err: errors.New(`ent: missing required edge "SocialSnapshot.candidate"`)}
	}
	return nil
}

func (_c *SocialSnapshotCreate) sqlSave(ctx context.Context) (*SocialSnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SocialSnapshotCreate) createSpec() (*SocialSnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &SocialSnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(socialsnapshot.Table, sqlgraph.NewFieldSpec(socialsnapshot.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SocialEvidence(); ok {
		_spec.SetField(socialsnapshot.FieldSocialEvidence, field.TypeJSON, value)
		_node.SocialEvidence = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(socialsnapshot.FieldScore, field.TypeInt, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.ObservedAt(); ok {
		_spec.SetField(socialsnapshot.FieldObservedAt, field.TypeTime, value)
		_node.ObservedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(socialsnapshot.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   socialsnapshot.CandidateTable,
			Columns: []string{socialsnapshot.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.candidate_social_snapshots = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SocialSnapshotCreateBulk is the builder for creating many SocialSnapshot entities in bulk.
type SocialSnapshotCreateBulk struct {
	config
	err      error
	builders []*SocialSnapshotCreate
}

// Save creates the SocialSnapshot entities in the database.
func (_c *SocialSnapshotCreateBulk) Save(ctx context.Context) ([]*SocialSnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SocialSnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SocialSnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SocialSnapshotCreateBulk) SaveX(ctx context.Context) []*SocialSnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SocialSnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SocialSnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
