// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/tradedecision"
)

// TradeDecisionCreate is the builder for creating a TradeDecision entity.
type TradeDecisionCreate struct {
	config
	mutation *TradeDecisionMutation
	hooks    []Hook
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *TradeDecisionCreate) SetIdempotencyKey(v string) *TradeDecisionCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetOutcome sets the "outcome" field.
func (_c *TradeDecisionCreate) SetOutcome(v string) *TradeDecisionCreate {
	_c.mutation.SetOutcome(v)
	return _c
}

// SetRuleResults sets the "rule_results" field.
func (_c *TradeDecisionCreate) SetRuleResults(v map[string]interface{}) *TradeDecisionCreate {
	_c.mutation.SetRuleResults(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TradeDecisionCreate) SetCreatedAt(v time.Time) *TradeDecisionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TradeDecisionCreate) SetNillableCreatedAt(v *time.Time) *TradeDecisionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_c *TradeDecisionCreate) SetCandidateID(id int) *TradeDecisionCreate {
	_c.mutation.SetCandidateID(id)
	return _c
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_c *TradeDecisionCreate) SetCandidate(v *Candidate) *TradeDecisionCreate {
	return _c.SetCandidateID(v.ID)
}

// Mutation returns the TradeDecisionMutation object of the builder.
func (_c *TradeDecisionCreate) Mutation() *TradeDecisionMutation {
	return _c.mutation
}

// Save creates the TradeDecision in the database.
func (_c *TradeDecisionCreate) Save(ctx context.Context) (*TradeDecision, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TradeDecisionCreate) SaveX(ctx context.Context) *TradeDecision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TradeDecisionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TradeDecisionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TradeDecisionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tradedecision.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TradeDecisionCreate) check() error {
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "TradeDecision.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := tradedecision.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "TradeDecision.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		return &ValidationError{Name: "outcome", err: errors.New(`ent: missing required field "TradeDecision.outcome"`)}
	}
	if v, ok := _c.mutation.Outcome(); ok {
		if err := tradedecision.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "TradeDecision.outcome": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RuleResults(); !ok {
		return &ValidationError{Name: "rule_results", err: errors.New(`ent: missing required field "TradeDecision.rule_results"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TradeDecision.created_at"`)}
	}
	if len(_c.mutation.CandidateIDs()) == 0 {
		return &ValidationError{Name: "candidate", err: errors.New(`ent: missing required edge "TradeDecision.candidate"`)}
	}
	return nil
}

func (_c *TradeDecisionCreate) sqlSave(ctx context.Context) (*TradeDecision, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TradeDecisionCreate) createSpec() (*TradeDecision, *sqlgraph.CreateSpec) {
	var (
		_node = &TradeDecision{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tradedecision.Table, sqlgraph.NewFieldSpec(tradedecision.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(tradedecision.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.Outcome(); ok {
		_spec.SetField(tradedecision.FieldOutcome, field.TypeString, value)
		_node.Outcome = value
	}
	if value, ok := _c.mutation.RuleResults(); ok {
		_spec.SetField(tradedecision.FieldRuleResults, field.TypeJSON, value)
		_node.RuleResults = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tradedecision.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tradedecision.CandidateTable,
			Columns: []string{tradedecision.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.candidate_decisions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TradeDecisionCreateBulk is the builder for creating many TradeDecision entities in bulk.
type TradeDecisionCreateBulk struct {
	config
	err      error
	builders []*TradeDecisionCreate
}

// Save creates the TradeDecision entities in the database.
func (_c *TradeDecisionCreateBulk) Save(ctx context.Context) ([]*TradeDecision, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TradeDecision, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TradeDecisionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TradeDecisionCreateBulk) SaveX(ctx context.Context) []*TradeDecision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TradeDecisionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TradeDecisionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
