// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/candidate"
	"github.com/SourceSenseiTheRealOne/solana-hype-paper-bot/ent/verdict"
)

// VerdictCreate is the builder for creating a Verdict entity.
type VerdictCreate struct {
	config
	mutation *VerdictMutation
	hooks    []Hook
}

// SetProvider sets the "provider" field.
func (_c *VerdictCreate) SetProvider(v string) *VerdictCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *VerdictCreate) SetModel(v string) *VerdictCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetOutcome sets the "outcome" field.
func (_c *VerdictCreate) SetOutcome(v string) *VerdictCreate {
	_c.mutation.SetOutcome(v)
	return _c
}

// SetEvidence sets the "evidence" field.
func (_c *VerdictCreate) SetEvidence(v map[string]interface{}) *VerdictCreate {
	_c.mutation.SetEvidence(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VerdictCreate) SetCreatedAt(v time.Time) *VerdictCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VerdictCreate) SetNillableCreatedAt(v *time.Time) *VerdictCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCandidateID sets the "candidate" edge to the Candidate entity by ID.
func (_c *VerdictCreate) SetCandidateID(id int) *VerdictCreate {
	_c.mutation.SetCandidateID(id)
	return _c
}

// SetCandidate sets the "candidate" edge to the Candidate entity.
func (_c *VerdictCreate) SetCandidate(v *Candidate) *VerdictCreate {
	return _c.SetCandidateID(v.ID)
}

// Mutation returns the VerdictMutation object of the builder.
func (_c *VerdictCreate) Mutation() *VerdictMutation {
	return _c.mutation
}

// Save creates the Verdict in the database.
func (_c *VerdictCreate) Save(ctx context.Context) (*Verdict, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VerdictCreate) SaveX(ctx context.Context) *Verdict {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VerdictCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VerdictCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VerdictCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := verdict.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VerdictCreate) check() error {
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "Verdict.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := verdict.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Verdict.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "Verdict.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := verdict.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "Verdict.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Outcome(); !ok {
		return &ValidationError{Name: "outcome", err: errors.New(`ent: missing required field "Verdict.outcome"`)}
	}
	if v, ok := _c.mutation.Outcome(); ok {
		if err := verdict.OutcomeValidator(v); err != nil {
			return &ValidationError{Name: "outcome", err: fmt.Errorf(`ent: validator failed for field "Verdict.outcome": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Evidence(); !ok {
		return &ValidationError{Name: "evidence", err: errors.New(`ent: missing required field "Verdict.evidence"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Verdict.created_at"`)}
	}
	if len(_c.mutation.CandidateIDs()) == 0 {
		return &ValidationError{Name: "candidate", err: errors.New(`ent: missing required edge "Verdict.candidate"`)}
	}
	return nil
}

func (_c *VerdictCreate) sqlSave(ctx context.Context) (*Verdict, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VerdictCreate) createSpec() (*Verdict, *sqlgraph.CreateSpec) {
	var (
		_node = &Verdict{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(verdict.Table, sqlgraph.NewFieldSpec(verdict.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(verdict.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(verdict.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Outcome(); ok {
		_spec.SetField(verdict.FieldOutcome, field.TypeString, value)
		_node.Outcome = value
	}
	if value, ok := _c.mutation.Evidence(); ok {
		_spec.SetField(verdict.FieldEvidence, field.TypeJSON, value)
		_node.Evidence = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(verdict.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CandidateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   verdict.CandidateTable,
			Columns: []string{verdict.CandidateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(candidate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.candidate_verdicts = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VerdictCreateBulk is the builder for creating many Verdict entities in bulk.
type VerdictCreateBulk struct {
	config
	err      error
	builders []*VerdictCreate
}

// Save creates the Verdict entities in the database.
func (_c *VerdictCreateBulk) Save(ctx context.Context) ([]*Verdict, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Verdict, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VerdictMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VerdictCreateBulk) SaveX(ctx context.Context) []*Verdict {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VerdictCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VerdictCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
