// Code generated by ent, DO NOT EDIT.

package apiusage

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the apiusage type in the database.
	Label = "api_usage"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldUtcDate holds the string denoting the utc_date field in the database.
	FieldUtcDate = "utc_date"
	// FieldRequestCount holds the string denoting the request_count field in the database.
	FieldRequestCount = "request_count"
	// FieldFailureCount holds the string denoting the failure_count field in the database.
	FieldFailureCount = "failure_count"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the apiusage in the database.
	Table = "api_usages"
)

// Columns holds all SQL columns for apiusage fields.
var Columns = []string{
	FieldID,
	FieldProvider,
	FieldUtcDate,
	FieldRequestCount,
	FieldFailureCount,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// RequestCountValidator is a validator for the "request_count" field. It is called by the builders before save.
	RequestCountValidator func(int) error
	// FailureCountValidator is a validator for the "failure_count" field. It is called by the builders before save.
	FailureCountValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the APIUsage queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByUtcDate orders the results by the utc_date field.
func ByUtcDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUtcDate, opts...).ToFunc()
}

// ByRequestCount orders the results by the request_count field.
func ByRequestCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestCount, opts...).ToFunc()
}

// ByFailureCount orders the results by the failure_count field.
func ByFailureCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureCount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
