// Code generated by ent, DO NOT EDIT.

package dailyresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the dailyresult type in the database.
	Label = "daily_result"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUtcDate holds the string denoting the utc_date field in the database.
	FieldUtcDate = "utc_date"
	// FieldStrategyVersion holds the string denoting the strategy_version field in the database.
	FieldStrategyVersion = "strategy_version"
	// FieldDailyAdmittedCount holds the string denoting the daily_admitted_count field in the database.
	FieldDailyAdmittedCount = "daily_admitted_count"
	// FieldRealizedPnlMicros holds the string denoting the realized_pnl_micros field in the database.
	FieldRealizedPnlMicros = "realized_pnl_micros"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the dailyresult in the database.
	Table = "daily_results"
)

// Columns holds all SQL columns for dailyresult fields.
var Columns = []string{
	FieldID,
	FieldUtcDate,
	FieldStrategyVersion,
	FieldDailyAdmittedCount,
	FieldRealizedPnlMicros,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// StrategyVersionValidator is a validator for the "strategy_version" field. It is called by the builders before save.
	StrategyVersionValidator func(string) error
	// DailyAdmittedCountValidator is a validator for the "daily_admitted_count" field. It is called by the builders before save.
	DailyAdmittedCountValidator func(int) error
	// DefaultRealizedPnlMicros holds the default value on creation for the "realized_pnl_micros" field.
	DefaultRealizedPnlMicros int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the DailyResult queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUtcDate orders the results by the utc_date field.
func ByUtcDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUtcDate, opts...).ToFunc()
}

// ByStrategyVersion orders the results by the strategy_version field.
func ByStrategyVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyVersion, opts...).ToFunc()
}

// ByDailyAdmittedCount orders the results by the daily_admitted_count field.
func ByDailyAdmittedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyAdmittedCount, opts...).ToFunc()
}

// ByRealizedPnlMicros orders the results by the realized_pnl_micros field.
func ByRealizedPnlMicros(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRealizedPnlMicros, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
