-- Create "api_usages" table
CREATE TABLE "api_usages" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "provider" character varying NOT NULL,
  "utc_date" timestamptz NOT NULL,
  "request_count" bigint NOT NULL,
  "failure_count" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "apiusage_provider_utc_date" to table: "api_usages"
CREATE UNIQUE INDEX "apiusage_provider_utc_date" ON "api_usages" ("provider", "utc_date");
-- Create "bot_states" table
CREATE TABLE "bot_states" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "state_key" character varying NOT NULL,
  "value" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "bot_states_state_key_key" to table: "bot_states"
CREATE UNIQUE INDEX "bot_states_state_key_key" ON "bot_states" ("state_key");
-- Create "candidates" table
CREATE TABLE "candidates" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "network" character varying NOT NULL,
  "mint_address" character varying NOT NULL,
  "pool_address" character varying NOT NULL,
  "discovered_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "candidate_network_mint_address_pool_address" to table: "candidates"
CREATE UNIQUE INDEX "candidate_network_mint_address_pool_address" ON "candidates" ("network", "mint_address", "pool_address");
-- Create "daily_results" table
CREATE TABLE "daily_results" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "utc_date" timestamptz NOT NULL,
  "strategy_version" character varying NOT NULL,
  "daily_admitted_count" bigint NOT NULL,
  "realized_pnl_micros" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "dailyresult_utc_date_strategy_version" to table: "daily_results"
CREATE UNIQUE INDEX "dailyresult_utc_date_strategy_version" ON "daily_results" ("utc_date", "strategy_version");
ALTER TABLE "daily_results" ADD CONSTRAINT "daily_results_daily_admitted_count_nonnegative" CHECK ("daily_admitted_count" >= 0);
ALTER TABLE "daily_results" ADD CONSTRAINT "daily_results_daily_admitted_count_maximum" CHECK ("daily_admitted_count" <= 30);
-- Create "candidate_snapshots" table
CREATE TABLE "candidate_snapshots" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "market_evidence" jsonb NOT NULL,
  "observed_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "candidate_snapshots" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "candidate_snapshots_candidates_snapshots" FOREIGN KEY ("candidate_snapshots") REFERENCES "candidates" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "paper_positions" table
CREATE TABLE "paper_positions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "state" character varying NOT NULL,
  "notional_micros" bigint NOT NULL,
  "entry_price" character varying NOT NULL,
  "token_quantity" character varying NOT NULL,
  "opened_at" timestamptz NULL,
  "closed_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "candidate_positions" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "paper_positions_candidates_positions" FOREIGN KEY ("candidate_positions") REFERENCES "candidates" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
ALTER TABLE "paper_positions" ADD CONSTRAINT "paper_positions_notional_micros_positive" CHECK ("notional_micros" > 0);
ALTER TABLE "paper_positions" ADD CONSTRAINT "paper_positions_state_valid" CHECK ("state" IN ('PENDING', 'OPEN', 'CLOSING', 'CLOSED', 'UNSELLABLE'));
-- Create "position_events" table
CREATE TABLE "position_events" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "event_type" character varying NOT NULL,
  "details" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL,
  "paper_position_events" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "position_events_paper_positions_events" FOREIGN KEY ("paper_position_events") REFERENCES "paper_positions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "position_marks" table
CREATE TABLE "position_marks" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "price" character varying NOT NULL,
  "observed_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "paper_position_marks" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "position_marks_paper_positions_marks" FOREIGN KEY ("paper_position_marks") REFERENCES "paper_positions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "social_snapshots" table
CREATE TABLE "social_snapshots" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "social_evidence" jsonb NOT NULL,
  "score" bigint NOT NULL,
  "observed_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  "candidate_social_snapshots" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "social_snapshots_candidates_social_snapshots" FOREIGN KEY ("candidate_social_snapshots") REFERENCES "candidates" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create "trade_decisions" table
CREATE TABLE "trade_decisions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "idempotency_key" character varying NOT NULL,
  "outcome" character varying NOT NULL,
  "rule_results" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL,
  "candidate_decisions" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "trade_decisions_candidates_decisions" FOREIGN KEY ("candidate_decisions") REFERENCES "candidates" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "tradedecision_idempotency_key" to table: "trade_decisions"
CREATE UNIQUE INDEX "tradedecision_idempotency_key" ON "trade_decisions" ("idempotency_key");
-- Create "verdicts" table
CREATE TABLE "verdicts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "provider" character varying NOT NULL,
  "model" character varying NOT NULL,
  "outcome" character varying NOT NULL,
  "evidence" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL,
  "candidate_verdicts" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "verdicts_candidates_verdicts" FOREIGN KEY ("candidate_verdicts") REFERENCES "candidates" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
