// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIUsage is the predicate function for apiusage builders.
type APIUsage func(*sql.Selector)

// BotState is the predicate function for botstate builders.
type BotState func(*sql.Selector)

// Candidate is the predicate function for candidate builders.
type Candidate func(*sql.Selector)

// CandidateSnapshot is the predicate function for candidatesnapshot builders.
type CandidateSnapshot func(*sql.Selector)

// DailyResult is the predicate function for dailyresult builders.
type DailyResult func(*sql.Selector)

// PaperPosition is the predicate function for paperposition builders.
type PaperPosition func(*sql.Selector)

// PositionEvent is the predicate function for positionevent builders.
type PositionEvent func(*sql.Selector)

// PositionMark is the predicate function for positionmark builders.
type PositionMark func(*sql.Selector)

// SocialSnapshot is the predicate function for socialsnapshot builders.
type SocialSnapshot func(*sql.Selector)

// TradeDecision is the predicate function for tradedecision builders.
type TradeDecision func(*sql.Selector)

// Verdict is the predicate function for verdict builders.
type Verdict func(*sql.Selector)
